/* 동화책 — 감자와 치즈가 나오는 짧은 이야기(운영자 결정 2026-10-03).
   배우기 › 동화책(#learn/stories)이 읽는다. app.module.js bkDraw.

   ── 저작권: 이 파일에서 가장 중요한 것 ─────────────────────
   **전부 새로 지은 이야기여야 한다.** 이미 있는 동화 · 전래동화 · 그림책 · 만화 · 영화 · 노래의
   줄거리 · 인물 · 문장 · 제목을 옮기거나 「조금 바꿔」 쓰지 않는다(흥부와 놀부 · 토끼와 거북이 ·
   신데렐라 · 뽀로로 같은 것 모두). 등장인물은 치즈감자의 감자 · 치즈와 이야기마다 새로 지은 이웃뿐.
   그림은 넣지 않는다 — 인물 얼굴은 levels.js 의 우리 그림(감자 · 치즈)만 쓴다.
   tools/check-stories.mjs 가 이름난 작품 · 인물 이름을 막는다(완벽하지 않다 — 검토가 먼저다).

   ── 밭 ───────────────────────────────────────────────────
   id     한 번 정하면 안 바꾼다(읽은 기록이 이 id 로 묶인다).
   lv     감자 레벨(1 = 입문 · 2 = 초급 · 3 = 초급 위). 문장 길이 · 문법을 그 레벨에 맞춘다.
   pages  [{ who, ko, en }] — 한 쪽에 한두 문장. who 는 그 쪽에서 말하는 이:
          'potato' 감자 · 'cheese' 치즈 · 'n' 해설(그 밖의 인물이 말해도 'n', 대사는 「이름: "…"」 꼴).
   words  이 이야기의 낱말 [{ ko, en }] — 본문에 실제로 나오는 꼴(또는 그 기본형).
   quiz   이해 확인 [{ q: { ko, en }, options: [한국어 넷], answer }] — answer 는 0부터. */

export const STORIES = [
  {
    id: 'sb-01', lv: 1,
    title: { ko: '비 오는 날의 우산', en: 'The Umbrella on a Rainy Day' },
    blurb: { ko: '빵을 사러 가야 하는데 우산이 없어요.', en: 'Potato needs bread, but there is no umbrella.' },
    pages: [
      { who: 'n',      ko: '아침에 비가 와요. 감자는 창밖을 봐요.', en: 'It is raining in the morning. Potato looks out the window.' },
      { who: 'potato', ko: '"아, 빵이 없어요. 빵집에 가야 해요."', en: '"Oh, there is no bread. I have to go to the bakery."' },
      { who: 'n',      ko: '감자는 우산을 찾아요. 그런데 우산이 없어요.', en: 'Potato looks for an umbrella. But there is no umbrella.' },
      { who: 'n',      ko: '그때 문이 열려요. 치즈가 노란 우산을 들고 서 있어요.', en: 'Just then the door opens. Cheese is standing there with a yellow umbrella.' },
      { who: 'cheese', ko: '"같이 가요! 제 우산은 커요."', en: '"Let’s go together! My umbrella is big."' },
      { who: 'n',      ko: '감자와 치즈는 우산 하나를 같이 쓰고 빵집에 가요.', en: 'Potato and Cheese share one umbrella and walk to the bakery.' },
      { who: 'potato', ko: '"치즈 씨, 고마워요. 빵은 제가 살게요!"', en: '"Thank you, Cheese. I’ll buy the bread!"' },
    ],
    words: [
      { ko: '비', en: 'rain' }, { ko: '우산', en: 'umbrella' }, { ko: '빵집', en: 'bakery' },
      { ko: '찾다', en: 'to look for' }, { ko: '같이', en: 'together' }, { ko: '고맙다', en: 'to be thankful' },
    ],
    quiz: [
      { q: { ko: '감자는 왜 밖에 나가요?', en: 'Why does Potato go out?' },
        options: ['빵을 사려고', '비를 보려고', '우산을 사려고', '치즈를 찾으려고'], answer: 0 },
      { q: { ko: '노란 우산은 누구의 우산이에요?', en: 'Whose is the yellow umbrella?' },
        options: ['감자', '빵집 사장님', '치즈', '감자의 엄마'], answer: 2 },
    ],
  },
  {
    id: 'sb-02', lv: 1,
    title: { ko: '치즈의 새 모자', en: "Cheese's New Hat" },
    blurb: { ko: '치즈가 시장에서 초록색 모자를 샀어요.', en: 'Cheese bought a green hat at the market.' },
    pages: [
      { who: 'n',      ko: '오늘 날씨가 조금 쌀쌀해요. 치즈는 시장에 가요.', en: 'The weather is a bit chilly today. Cheese goes to the market.' },
      { who: 'n',      ko: '모자 가게에 예쁜 모자가 많아요. 치즈는 초록색 털모자를 골라요.', en: 'There are many pretty hats at the hat shop. Cheese picks a green knit hat.' },
      { who: 'n',      ko: '치즈가 모자를 쓰고 감자의 집에 가요.', en: "Cheese puts on the hat and goes to Potato's house." },
      { who: 'potato', ko: '"어? 치즈 씨, 머리에 브로콜리가 있어요!"', en: '"Huh? Cheese, there’s broccoli on your head!"' },
      { who: 'cheese', ko: '"아니에요. 이건 제 새 모자예요."', en: '"No, it’s not. This is my new hat."' },
      { who: 'potato', ko: '"정말 귀여워요! 치즈 씨한테 잘 어울려요."', en: '"It is really cute! It suits you so well, Cheese."' },
      { who: 'n',      ko: '두 친구는 함께 웃으며 산책을 가요.', en: 'The two friends laugh together and go for a walk.' },
    ],
    words: [
      { ko: '쌀쌀하다', en: 'to be chilly' }, { ko: '모자', en: 'hat' }, { ko: '고르다', en: 'to choose, pick' },
      { ko: '귀엽다', en: 'to be cute' }, { ko: '어울리다', en: 'to suit' }, { ko: '산책', en: 'walk, stroll' },
    ],
    quiz: [
      { q: { ko: '치즈는 무슨 색 모자를 샀어요?', en: 'What color hat did Cheese buy?' },
        options: ['노란색', '초록색', '파란색', '빨간색'], answer: 1 },
      { q: { ko: '감자는 모자를 보고 무엇 같다고 했어요?', en: 'What did Potato say the hat looked like?' },
        options: ['사과', '나무', '브로콜리', '우산'], answer: 2 },
    ],
  },
  {
    id: 'sb-03', lv: 1,
    title: { ko: '조용한 도서관', en: 'The Quiet Library' },
    blurb: { ko: '감자와 치즈가 동네 도서관에 가요.', en: 'Potato and Cheese go to the neighborhood library.' },
    pages: [
      { who: 'n',      ko: '오후에 감자와 치즈는 동네 도서관에 가요.', en: 'In the afternoon, Potato and Cheese go to the neighborhood library.' },
      { who: 'n',      ko: '도서관 안은 아주 조용해요. 사람들이 책을 읽어요.', en: 'Inside the library is very quiet. People are reading books.' },
      { who: 'potato', ko: '"치즈 씨, 저는 그림책을 볼래요."', en: '"Cheese, I want to look at a picture book."' },
      { who: 'cheese', ko: '"좋아요. 저는 요리책을 찾을게요."', en: '"Sounds good. I will look for a cookbook."' },
      { who: 'n',      ko: '잠시 뒤에 감자가 치즈를 봐요. 치즈가 책상에서 자요.', en: 'A moment later, Potato looks at Cheese. Cheese is sleeping at the desk.' },
      { who: 'potato', ko: '"치즈 씨, 여기서 자면 안 돼요. 일어나세요."', en: '"Cheese, you cannot sleep here. Please wake up."' },
      { who: 'n',      ko: '치즈가 눈을 비벼요. 두 친구는 작게 웃어요.', en: 'Cheese rubs sleepy eyes. The two friends laugh quietly.' },
    ],
    words: [
      { ko: '조용하다', en: 'to be quiet' }, { ko: '그림책', en: 'picture book' }, { ko: '요리책', en: 'cookbook' },
      { ko: '잠시', en: 'a moment' }, { ko: '일어나다', en: 'to wake up' }, { ko: '비비다', en: 'to rub' },
    ],
    quiz: [
      { q: { ko: '감자는 도서관에서 무슨 책을 봐요?', en: 'What book does Potato look at in the library?' },
        options: ['그림책', '만화책', '요리책', '신문'], answer: 0 },
      { q: { ko: '치즈는 책상에서 무엇을 했어요?', en: 'What did Cheese do at the desk?' },
        options: ['노래했어요', '그림을 그렸어요', '밥을 먹었어요', '잠을 잤어요'], answer: 3 },
    ],
  },
  {
    id: 'sb-04', lv: 1,
    title: { ko: '초록색 버스', en: 'The Green Bus' },
    blurb: { ko: '버스 정류장에서 버스를 기다려요.', en: 'Waiting for the bus at the bus stop.' },
    pages: [
      { who: 'n',      ko: '감자와 치즈는 버스 정류장에 서 있어요.', en: 'Potato and Cheese are standing at the bus stop.' },
      { who: 'potato', ko: '"치즈 씨, 우리 버스가 언제 와요?"', en: '"Cheese, when is our bus coming?"' },
      { who: 'cheese', ko: '"조금만 기다려요. 곧 올 거예요."', en: '"Let’s wait a little. It will come soon."' },
      { who: 'n',      ko: '자동차가 많이 지나가요. 두 친구는 노란 차를 세어요.', en: 'Many cars pass by. The two friends count yellow cars.' },
      { who: 'potato', ko: '"하나, 둘, 셋, 넷, 다섯!"', en: '"One, two, three, four, five!"' },
      { who: 'cheese', ko: '"아, 저기 초록색 버스가 와요!"', en: '"Ah, over there the green bus is coming!"' },
      { who: 'n',      ko: '감자와 치즈는 반갑게 버스에 올라요.', en: 'Potato and Cheese happily get on the bus.' },
    ],
    words: [
      { ko: '정류장', en: 'bus stop' }, { ko: '기다리다', en: 'to wait' }, { ko: '지나가다', en: 'to pass by' },
      { ko: '세다', en: 'to count' }, { ko: '초록색', en: 'green color' }, { ko: '반갑다', en: 'to be glad' },
    ],
    quiz: [
      { q: { ko: '두 친구는 기다리면서 무슨 색 차를 세었어요?', en: 'What color cars did the two friends count while waiting?' },
        options: ['빨간 차', '검은 차', '하얀 차', '노란 차'], answer: 3 },
      { q: { ko: '두 사람이 탄 버스는 무슨 색이에요?', en: 'What color is the bus that the two people boarded?' },
        options: ['초록색', '파란색', '노란색', '주황색'], answer: 0 },
    ],
  },
  {
    id: 'sb-05', lv: 1,
    title: { ko: '따뜻한 붕어빵', en: 'Warm Fish-Shaped Bread' },
    blurb: { ko: '추운 저녁에 달콤한 붕어빵을 사요.', en: 'Buying sweet fish-shaped bread on a cold evening.' },
    pages: [
      { who: 'n',      ko: '겨울 저녁이에요. 바람이 불고 날씨가 추워요.', en: 'It is a winter evening. The wind blows and the weather is cold.' },
      { who: 'n',      ko: '길모퉁이에서 달콤하고 고소한 냄새가 나요.', en: 'A sweet and savory smell comes from the street corner.' },
      { who: 'potato', ko: '"치즈 씨, 저기 붕어빵 가게가 있어요!"', en: '"Cheese, there is a fish bread stand over there!"' },
      { who: 'cheese', ko: '"와, 맛있겠어요! 팥 붕어빵을 먹어요."', en: '"Wow, that looks delicious! Let’s eat red bean fish bread."' },
      { who: 'n',      ko: '감자는 천 원을 내고 붕어빵 두 개를 받아요.', en: 'Potato pays one thousand won and gets two fish breads.' },
      { who: 'cheese', ko: '"앗, 너무 뜨거워요! 호호 불어서 먹어야 해요."', en: '"Ouch, it is so hot! I have to blow on it to eat."' },
      { who: 'n',      ko: '두 친구는 따뜻한 붕어빵을 먹으며 집으로 걸어가요.', en: 'The two friends eat the warm fish bread and walk home.' },
    ],
    words: [
      { ko: '겨울', en: 'winter' }, { ko: '바람', en: 'wind' }, { ko: '냄새', en: 'smell, aroma' },
      { ko: '팥', en: 'red bean' }, { ko: '뜨겁다', en: 'to be hot' }, { ko: '걸어가다', en: 'to walk' },
    ],
    quiz: [
      { q: { ko: '감자는 붕어빵을 몇 개 샀어요?', en: 'How many fish breads did Potato buy?' },
        options: ['한 개', '두 개', '세 개', '네 개'], answer: 1 },
      { q: { ko: '붕어빵 안에는 무엇이 들어 있어요?', en: 'What is inside the fish bread?' },
        options: ['치즈', '감자', '팥', '초콜릿'], answer: 2 },
    ],
  },
  {
    id: 'sb-06', lv: 2,
    title: { ko: '옆집 할머니의 감나무', en: 'The Persimmon Tree of the Grandmother Next Door' },
    blurb: { ko: '가을에 옆집 할머니의 감 따기를 도와드려요.', en: 'Helping the neighbor grandmother pick persimmons in autumn.' },
    pages: [
      { who: 'n',      ko: '가을이 되어서 옆집 마당의 감나무에 주황색 감이 가득 열렸어요.', en: 'Autumn came, and the persimmon tree in the neighbor’s yard was full of orange persimmons.' },
      { who: 'n',      ko: '옆집 할머니가 마당에서 긴 장대를 들고 서 계셨어요.', en: 'The grandmother next door was standing in the yard holding a long pole.' },
      { who: 'potato', ko: '"할머니, 높은 곳에 있는 감이 안 닿으세요? 저희가 도와드릴게요."', en: '"Grandmother, can’t you reach the persimmons up high? We will help you."' },
      { who: 'cheese', ko: '"제가 상자를 잡고 있을 테니 감을 여기에 담으세요."', en: '"I will hold the box, so please put the persimmons in here."' },
      { who: 'n',      ko: '감자와 치즈는 할머니와 함께 잘 익은 감을 조심조심 땄어요.', en: 'Potato and Cheese carefully picked ripe persimmons together with the grandmother.' },
      { who: 'n',      ko: '할머니가 활짝 웃으며 말해요. "도와줘서 정말 고마워요. 이 감을 가져가서 맛있게 먹어요."', en: 'The grandmother smiled brightly and said: "Thank you so much for helping. Take these persimmons and enjoy them."' },
      { who: 'n',      ko: '두 친구는 달콤한 감을 한 바구니 들고 기쁘게 돌아왔어요.', en: 'The two friends came back happily carrying a basket of sweet persimmons.' },
    ],
    words: [
      { ko: '가을', en: 'autumn' }, { ko: '마당', en: 'yard' }, { ko: '장대', en: 'pole' },
      { ko: '담다', en: 'to put in' }, { ko: '익다', en: 'to ripen' }, { ko: '바구니', en: 'basket' },
    ],
    quiz: [
      { q: { ko: '할머니 마당에는 무슨 나무가 있었어요?', en: 'What tree was in the grandmother’s yard?' },
        options: ['감나무', '사과나무', '복숭아나무', '단풍나무'], answer: 0 },
      { q: { ko: '치즈는 감을 딸 때 무엇을 잡고 있었어요?', en: 'What was Cheese holding while picking persimmons?' },
        options: ['사다리', '우산', '장대', '상자'], answer: 3 },
    ],
  },
  {
    id: 'sb-07', lv: 2,
    title: { ko: '시장의 반찬 가게', en: 'The Market Side Dish Shop' },
    blurb: { ko: '저녁에 먹을 맛있는 반찬을 사러 가요.', en: 'Going to buy delicious side dishes for dinner.' },
    pages: [
      { who: 'n',      ko: '저녁 시간이 다 되었는데 냉장고에 반찬이 하나도 없었어요.', en: 'It was dinner time, but there were no side dishes in the refrigerator.' },
      { who: 'cheese', ko: '"감자 씨, 우리 전통시장에 있는 반찬 가게에 가요."', en: '"Potato, let’s go to the side dish shop in the traditional market."' },
      { who: 'n',      ko: '반찬 가게에는 김치, 멸치볶음, 계란말이가 줄지어 놓여 있었어요.', en: 'At the side dish shop, kimchi, stir-fried anchovies, and rolled omelet were lined up.' },
      { who: 'n',      ko: '가게 사장님이 이쑤시개에 계란말이를 꽂아 주셨어요. "방금 만들었으니 맛보세요."', en: 'The shop owner handed over rolled omelet on a toothpick: "I just made it, give it a taste."' },
      { who: 'potato', ko: '"정말 부드럽고 맛있어요! 계란말이랑 멸치볶음 주세요."', en: '"It is really soft and delicious! Please give us rolled omelet and stir-fried anchovies."' },
      { who: 'n',      ko: '치즈가 반찬 통을 가방에 넣고 두 사람은 집으로 향했어요.', en: 'Cheese put the side dish containers in the bag, and the two headed home.' },
      { who: 'n',      ko: '감자가 지은 따뜻한 밥에 맛있는 반찬을 얹어서 배부르게 먹었어요.', en: 'They put the tasty side dishes on the warm rice Potato had cooked and ate until they were full.' },
    ],
    words: [
      { ko: '냉장고', en: 'refrigerator' }, { ko: '전통시장', en: 'traditional market' }, { ko: '반찬', en: 'side dish' },
      { ko: '맛보다', en: 'to taste' }, { ko: '부드럽다', en: 'to be soft' }, { ko: '배부르다', en: 'to be full' },
    ],
    quiz: [
      { q: { ko: '가게 사장님이 맛보라고 준 반찬은 무엇이에요?', en: 'What side dish did the shop owner offer to taste?' },
        options: ['계란말이', '멸치볶음', '김치', '두부조림'], answer: 0 },
      { q: { ko: '두 사람은 반찬을 몇 가지 샀어요?', en: 'How many side dishes did the two buy for dinner?' },
        options: ['한 가지', '두 가지', '세 가지', '네 가지'], answer: 1 },
    ],
  },
  {
    id: 'sb-08', lv: 2,
    title: { ko: '공원의 작은 고양이', en: 'The Little Cat in the Park' },
    blurb: { ko: '공원 벤치 밑에서 작은 고양이를 만났어요.', en: 'Met a little cat under the park bench.' },
    pages: [
      { who: 'n',      ko: '따뜻한 햇살이 비치는 주말 오후였어요. 감자와 치즈는 공원을 걸었어요.', en: 'It was a weekend afternoon with warm sunshine. Potato and Cheese walked in the park.' },
      { who: 'n',      ko: '벤치 밑에서 조그만 하얀 고양이가 "야옹" 하고 울었어요.', en: 'Under the bench, a tiny white cat meowed.' },
      { who: 'potato', ko: '"치즈 씨, 저기 보세요. 목줄에 방울이 달려 있어요."', en: '"Cheese, look over there. A bell is hanging on its collar."' },
      { who: 'cheese', ko: '"목줄이 있는 것을 보니 집을 잃어버린 고양이 같아요."', en: '"Seeing that it has a collar, it seems like a lost cat."' },
      { who: 'n',      ko: '감자는 손수건을 펴서 고양이 앞에 앉았고, 치즈는 작은 종이컵에 물을 담아 주었어요.', en: 'Potato spread a handkerchief and sat in front of the cat, and Cheese offered water in a small paper cup.' },
      { who: 'n',      ko: '잠시 후 한 아이가 울면서 공원으로 뛰어왔어요. "나비야, 어디 갔었어!"', en: 'A moment later, a child ran into the park crying: "Nabi, where were you!"' },
      { who: 'cheese', ko: '"여기 벤치 밑에 있어요! 다치지 않았어요."', en: '"It is here under the bench! It is not hurt."' },
      { who: 'n',      ko: '아이와 부모님이 감자와 치즈에게 연신 고개를 숙이며 고마워했어요.', en: 'The child and parents bowed repeatedly to Potato and Cheese, thanking them warmly.' },
    ],
    words: [
      { ko: '햇살', en: 'sunshine' }, { ko: '벤치', en: 'bench' }, { ko: '방울', en: 'bell' },
      { ko: '목줄', en: 'collar, leash' }, { ko: '손수건', en: 'handkerchief' }, { ko: '다치다', en: 'to get hurt' },
    ],
    quiz: [
      { q: { ko: '고양이는 처음에 어디에 있었어요?', en: 'Where was the cat at first?' },
        options: ['나무 위', '풀밭 속', '그네 옆', '벤치 밑'], answer: 3 },
      { q: { ko: '고양이의 목줄에는 무엇이 달려 있었어요?', en: 'What was hanging on the cat’s collar?' },
        options: ['이름표', '열쇠', '방울', '리본'], answer: 2 },
    ],
  },
  {
    id: 'sb-09', lv: 2,
    title: { ko: '깜짝 생일 파티', en: 'The Surprise Birthday Party' },
    blurb: { ko: '치즈의 생일에 감자가 몰래 케이크를 준비해요.', en: 'Potato secretly prepares a cake for Cheese’s birthday.' },
    pages: [
      { who: 'n',      ko: '오늘은 치즈의 생일이었어요. 하지만 치즈는 회사 일 때문에 늦게까지 일했어요.', en: 'Today was Cheese’s birthday. But Cheese worked late because of company work.' },
      { who: 'n',      ko: '감자는 치즈가 모르게 동네 빵집에 들러 딸기 케이크를 샀어요.', en: 'Potato stopped by the neighborhood bakery without Cheese knowing and bought a strawberry cake.' },
      { who: 'potato', ko: '"치즈 씨가 오면 깜짝 놀라게 해 줘야지!"', en: '"When Cheese comes, I will surprise Cheese!"' },
      { who: 'n',      ko: '감자는 식탁 위에 알록달록한 고깔모자와 케이크를 올려놓았어요.', en: 'Potato placed a colorful party hat and the cake on the dining table.' },
      { who: 'n',      ko: '밤이 깊어 현관문 도어록 소리가 났어요. 감자는 불을 끄고 촛불을 켰어요.', en: 'Deep into the night, the front door lock sounded. Potato turned off the lights and lit a candle.' },
      { who: 'cheese', ko: '"집이 왜 이렇게 캄캄하지? 감자 씨, 계세요?"', en: '"Why is the house so dark? Potato, are you there?"' },
      { who: 'potato', ko: '"생일 축하해요, 치즈 씨! 촛불을 불어 보세요."', en: '"Happy birthday, Cheese! Blow out the candle."' },
      { who: 'n',      ko: '치즈는 피곤함도 잊은 채 환하게 웃으며 소원을 빌었어요.', en: 'Cheese smiled brightly, forgetting all fatigue, and made a wish.' },
    ],
    words: [
      { ko: '빵집', en: 'bakery' }, { ko: '식탁', en: 'dining table' }, { ko: '촛불', en: 'candlelight' },
      { ko: '캄캄하다', en: 'to be dark' }, { ko: '피곤하다', en: 'to be tired' }, { ko: '소원', en: 'wish' },
    ],
    quiz: [
      { q: { ko: '감자가 빵집에서 사 온 케이크는 무슨 케이크예요?', en: 'What cake did Potato buy at the bakery?' },
        options: ['초코 케이크', '치즈 케이크', '딸기 케이크', '사과 케이크'], answer: 2 },
      { q: { ko: '현관문 소리가 났을 때 감자는 무엇을 켰어요?', en: 'What did Potato light when the front door sounded?' },
        options: ['텔레비전', '촛불', '형광등', '컴퓨터'], answer: 1 },
    ],
  },
  {
    id: 'sb-10', lv: 3,
    title: { ko: '토요일의 벼룩시장', en: 'The Saturday Flea Market' },
    blurb: { ko: '동네 공원에서 열린 벼룩시장에 물건을 가지고 가요.', en: 'Taking items to the flea market held at the neighborhood park.' },
    pages: [
      { who: 'n',      ko: '맑은 토요일 아침, 동네 공원 잔디밭에서 주민들이 참여하는 벼룩시장이 열렸습니다.', en: 'On a clear Saturday morning, a flea market joined by local residents opened on the park lawn.' },
      { who: 'n',      ko: '감자는 집에서 깨끗하게 닦아 둔 유리컵을, 치즈는 직접 만든 천 책갈피를 챙겨 나왔습니다.', en: 'Potato brought clean glass cups from home, and Cheese brought handmade cloth bookmarks.' },
      { who: 'cheese', ko: '"손수 만든 책갈피를 좋아해 줄 사람이 있을지 조금 걱정돼요."', en: '"I am a little worried whether anyone will like my handmade bookmarks."' },
      { who: 'potato', ko: '"색깔이 아주 고와서 분명히 인기가 많을 거예요. 걱정하지 마세요."', en: '"The colors are so lovely that they will definitely be popular. Do not worry."' },
      { who: 'n',      ko: '자리를 펴자마자 이웃집 아주머니가 다가와 감자의 유리컵을 보며 반가워했습니다. "마침 화채 그릇으로 쓸 예쁜 컵이 필요했어요."', en: 'As soon as they set up, a neighbor came over and admired Potato’s cups: "I happened to need pretty cups for fruit punch."' },
      { who: 'n',      ko: '책을 든 한 학생도 치즈의 책갈피를 여러 개 고르며 정성이 가득 담겼다고 칭찬했습니다.', en: 'A student holding a book also picked several of Cheese’s bookmarks, praising how much care went into them.' },
      { who: 'potato', ko: '"돈을 많이 벌지는 못했지만, 이웃들과 따뜻한 이야기를 나눌 수 있어서 정말 보람찼어요."', en: '"We didn’t earn a lot of money, but it was truly rewarding to share warm conversations with neighbors."' },
      { who: 'n',      ko: '두 친구는 남은 짐을 정리하며 다음 달 벼룩시장에도 꼭 다시 참여하기로 약속했습니다.', en: 'Packing up the remaining items, the two friends promised to participate again in next month’s flea market.' },
    ],
    words: [
      { ko: '벼룩시장', en: 'flea market' }, { ko: '잔디밭', en: 'lawn, grassy field' }, { ko: '유리컵', en: 'glass cup' },
      { ko: '책갈피', en: 'bookmark' }, { ko: '정성', en: 'care, devotion' }, { ko: '보람차다', en: 'to be rewarding' },
    ],
    quiz: [
      { q: { ko: '치즈가 벼룩시장에 직접 만들어 가져간 물건은 무엇입니까?', en: 'What item did Cheese make and bring to the flea market?' },
        options: ['천 책갈피', '유리컵', '그림책', '꽃바구니'], answer: 0 },
      { q: { ko: '이웃집 아주머니는 유리컵을 무엇으로 쓰려고 샀습니까?', en: 'What did the neighbor woman buy the glass cups for?' },
        options: ['커피 잔', '물병', '화분', '화채 그릇'], answer: 3 },
    ],
  },
  {
    id: 'sb-11', lv: 3,
    title: { ko: '첫눈 오는 날의 작은 눈사람', en: 'The Little Snowman on the Day of First Snow' },
    blurb: { ko: '온 세상이 하얗게 변한 날, 언덕길을 걸어요.', en: 'Walking up the hill on a day when the whole world turned white.' },
    pages: [
      { who: 'n',      ko: '창문을 열자 밤새 내린 첫눈으로 온 동네의 지붕과 골목길이 하얗게 덮여 있었습니다.', en: 'When opening the window, all the roofs and alleys of the neighborhood were covered in white from the first snow that fell overnight.' },
      { who: 'potato', ko: '"치즈 씨, 밖을 보세요! 눈이 소복하게 쌓였어요. 우리 동네 뒷산 언덕에 올라가 봐요."', en: '"Cheese, look outside! Snow has piled up softly. Let’s go up the hill behind our neighborhood."' },
      { who: 'cheese', ko: '"길이 미끄러우니까 두꺼운 털장갑을 끼고 따뜻한 목도리를 두르고 나가요."', en: '"The road is slippery, so let’s put on thick mittens and wrap a warm scarf before going out."' },
      { who: 'n',      ko: '두 친구는 뽀드득뽀드득 눈을 밟으며 언덕 정상에 있는 정자로 천천히 걸어 올라갔습니다.', en: 'The two friends stepped crunchily on the snow and slowly walked up to the pavilion at the top of the hill.' },
      { who: 'potato', ko: '"여기에 우리를 닮은 눈사람을 만들어 볼까요? 치즈 씨는 세모난 치즈 모양 눈사람을 만들어 보세요."', en: '"Shall we build snowmen that look like us here? Cheese, try making a triangle cheese-shaped one."' },
      { who: 'n',      ko: '감자는 둥글둥글한 감자 모양 눈사람을, 치즈는 세모난 치즈 모양 눈사람을 빚고 작은 나뭇가지로 얼굴을 장식했습니다.', en: 'Potato shaped a round potato snowman and Cheese a triangle cheese snowman, and they decorated the faces with small twigs.' },
      { who: 'cheese', ko: '"어머, 나란히 서 있는 모습이 꼭 우리 둘 같아요. 정말 다정해 보여요."', en: '"Oh my, standing side by side they look just like the two of us. They look so sweet."' },
      { who: 'n',      ko: '차가운 겨울바람 속에서도 두 친구의 마음은 모락모락 김이 나는 찻잔처럼 훈훈했습니다.', en: 'Even in the cold winter wind, the two friends’ hearts were warm like a steaming teacup.' },
    ],
    words: [
      { ko: '첫눈', en: 'first snow' }, { ko: '소복하다', en: 'to be piled high' }, { ko: '미끄럽다', en: 'to be slippery' },
      { ko: '밟다', en: 'to step on' }, { ko: '장식하다', en: 'to decorate' }, { ko: '훈훈하다', en: 'to be warm-hearted' },
    ],
    quiz: [
      { q: { ko: '두 친구는 어디로 걸어 올라갔습니까?', en: 'Where did the two friends walk up to?' },
        options: ['도서관 옥상', '지하철역 출구', '언덕 정상의 정자', '전통시장 입구'], answer: 2 },
      { q: { ko: '두 사람이 정자에서 만든 것은 무엇입니까?', en: 'What did the two people make at the pavilion?' },
        options: ['얼음 썰매', '두 개의 작은 눈사람', '따뜻한 모닥불', '눈으로 만든 성'], answer: 1 },
    ],
  },
  {
    id: 'sb-12', lv: 1,
    title: { ko: "아침 빵집 나들이", en: "Morning Bakery Outing" },
    blurb: { ko: "아침 일찍 빵집에서 고소한 빵을 사요.", en: "Buying fragrant bread early in the morning at the bakery." },
    pages: [
      { who: 'n',       ko: "아침 해가 밝아요. 감자가 일찍 일어나요.", en: "The morning sun is bright. Potato wakes up early." },
      { who: 'potato',  ko: "\"오늘 아침에는 따뜻한 식빵이 먹고 싶어요.\"", en: "\"This morning I want to eat warm plain bread.\"" },
      { who: 'n',       ko: "감자는 모자를 쓰고 빵집으로 걸어가요.", en: "Potato puts on a hat and walks to the bakery." },
      { who: 'n',       ko: "빵집 문을 열어요. 달콤한 냄새가 가득해요.", en: "Potato opens the bakery door. It is full of sweet smells." },
      { who: 'n',       ko: "치즈가 빵집 안에서 쟁반을 들고 서 있어요.", en: "Cheese is standing inside the bakery holding a tray." },
      { who: 'cheese',  ko: "\"감자 씨, 안녕하세요! 방금 나온 빵이 아주 따뜻해요.\"", en: "\"Hello, Potato! The freshly baked bread is very warm.\"" },
      { who: 'potato',  ko: "\"치즈 씨, 반가워요! 우리 갓 구운 식빵을 같이 사요.\"", en: "\"Nice to see you, Cheese! Let's buy freshly baked bread together.\"" },
      { who: 'n',       ko: "두 친구는 빵을 사고 기분 좋게 집으로 가요.", en: "The two friends buy bread and head home cheerfully." },
    ],
    words: [
      { ko: "일어나다", en: "to wake up" },
      { ko: "식빵", en: "plain white bread" },
      { ko: "냄새", en: "smell, scent" },
      { ko: "쟁반", en: "tray" },
      { ko: "방금", en: "just now" },
      { ko: "따뜻하다", en: "to be warm" },
    ],
    quiz: [
      { q: { ko: "감자는 아침에 어디에 갔어요?", en: "Where did Potato go in the morning?" },
        options: ["빵집", "서점", "은행", "공원"], answer: 0 },
      { q: { ko: "치즈는 손에 무엇을 들고 있었어요?", en: "What was Cheese holding in hand?" },
        options: ["가방", "우산", "쟁반", "꽃"], answer: 2 },
    ],
  },
  {
    id: 'sb-13', lv: 1,
    title: { ko: "파란 버스를 타는 날", en: "Riding the Blue Bus" },
    blurb: { ko: "감자와 치즈가 정류장에서 버스를 기다려요.", en: "Potato and Cheese wait for the bus at the stop." },
    pages: [
      { who: 'n',       ko: "날씨가 맑아요. 감자와 치즈가 버스 정류장에 서 있어요.", en: "The weather is clear. Potato and Cheese stand at the bus stop." },
      { who: 'potato',  ko: "\"치즈 씨, 오늘 시내 서점에 가고 싶어요.\"", en: "\"Cheese, I want to go to the downtown bookstore today.\"" },
      { who: 'cheese',  ko: "\"좋아요! 저기 파란 버스가 와요. 카드를 준비하세요.\"", en: "\"Great! Over there comes the blue bus. Please get your card ready.\"" },
      { who: 'n',       ko: "파란 버스가 정류장에 서요. 문이 스르륵 열려요.", en: "The blue bus stops at the station. The door opens smoothly." },
      { who: 'n',       ko: "감자와 치즈가 버스에 올라요. 카드를 삑 찍어요.", en: "Potato and Cheese board the bus. They beep their cards." },
      { who: 'cheese',  ko: "\"창문 옆자리가 비었어요. 어서 앉으세요.\"", en: "\"The seat by the window is empty. Please sit down quickly.\"" },
      { who: 'potato',  ko: "\"창밖 풍경이 참 예뻐요. 버스 타기는 즐거워요.\"", en: "\"The view outside the window is so pretty. Riding the bus is fun.\"" },
      { who: 'n',       ko: "버스가 부드럽게 달려요. 두 친구는 서점으로 가요.", en: "The bus runs smoothly. The two friends head to the bookstore." },
    ],
    words: [
      { ko: "정류장", en: "bus stop" },
      { ko: "서점", en: "bookstore" },
      { ko: "준비하다", en: "to prepare" },
      { ko: "오르다", en: "to board, climb" },
      { ko: "앉다", en: "to sit" },
      { ko: "풍경", en: "scenery, view" },
    ],
    quiz: [
      { q: { ko: "두 친구는 무슨 색 버스를 탔어요?", en: "What color bus did the two friends ride?" },
        options: ["노란 버스", "파란 버스", "초록 버스", "빨간 버스"], answer: 1 },
      { q: { ko: "두 사람은 어디에 가려고 해요?", en: "Where are the two people planning to go?" },
        options: ["동물원", "수영장", "도서관", "서점"], answer: 3 },
    ],
  },
  {
    id: 'sb-14', lv: 1,
    title: { ko: "새 화분을 사요", en: "Buying a New Flowerpot" },
    blurb: { ko: "동네 꽃집에서 작은 화분을 골라요.", en: "Picking a small flowerpot at the neighborhood flower shop." },
    pages: [
      { who: 'n',       ko: "봄바람이 살랑살랑 불어요. 감자가 창문을 활짝 열어요.", en: "Spring wind blows gently. Potato opens the window wide." },
      { who: 'potato',  ko: "\"창가에 둘 예쁜 꽃 화분을 하나 사고 싶어요.\"", en: "\"I want to buy a pretty flowerpot to place by the window.\"" },
      { who: 'n',       ko: "치즈가 꽃집 앞 화분들을 구경하고 있어요.", en: "Cheese is looking at flowerpots in front of the flower shop." },
      { who: 'cheese',  ko: "\"감자 씨, 이리 오세요! 노란 꽃이 핀 화분이 있어요.\"", en: "\"Potato, come here! There is a flowerpot with yellow flowers in bloom.\"" },
      { who: 'potato',  ko: "\"정말 귀여워요! 잎도 싱싱하고 초록빛이에요.\"", en: "\"It is so cute! The leaves are fresh and green too.\"" },
      { who: 'n',       ko: "꽃집 사장님이 나와요. 화분에 물을 듬뿍 줘요.", en: "The flower shop owner comes out. The owner gives plenty of water to the pot." },
      { who: 'cheese',  ko: "\"사장님, 물은 며칠에 한 번 줘요?\"", en: "\"Owner, how often do we give water?\"" },
      { who: 'n',       ko: "\"사흘에 한 번 듬뿍 주세요.\" 사장님이 웃으며 말해요.", en: "\"Please give plenty once every three days,\" the owner says with a smile." },
      { who: 'potato',  ko: "\"매일 아침 사랑으로 잘 돌볼게요. 고맙습니다!\"", en: "\"I will take good care of it with love every morning. Thank you!\"" },
    ],
    words: [
      { ko: "화분", en: "flowerpot" },
      { ko: "창가", en: "window side" },
      { ko: "구경하다", en: "to look around" },
      { ko: "싱싱하다", en: "to be fresh" },
      { ko: "돌보다", en: "to take care of" },
      { ko: "꽃", en: "flower" },
    ],
    quiz: [
      { q: { ko: "감자가 사고 싶어 한 것은 무엇이에요?", en: "What did Potato want to buy?" },
        options: ["꽃 화분", "모자", "가방", "책"], answer: 0 },
      { q: { ko: "화분에 물은 며칠에 한 번 줘요?", en: "How often should water be given to the pot?" },
        options: ["하루에 한 번", "사흘에 한 번", "일주일에 한 번", "한 달에 한 번"], answer: 1 },
    ],
  },
  {
    id: 'sb-15', lv: 1,
    title: { ko: "오후의 과일 가게", en: "Afternoon Fruit Store" },
    blurb: { ko: "달콤한 과일을 사러 과일 가게에 가요.", en: "Going to the fruit store to buy sweet fruits." },
    pages: [
      { who: 'n',       ko: "따뜻한 오후예요. 치즈가 바구니를 들고 길을 나서요.", en: "It is a warm afternoon. Cheese steps out with a basket." },
      { who: 'cheese',  ko: "\"오늘 간식으로 달콤한 과일을 먹고 싶어요.\"", en: "\"I want to eat sweet fruit for snack today.\"" },
      { who: 'n',       ko: "동네 과일 가게 앞에 붉은 사과와 딸기가 가득해요.", en: "In front of the local fruit store, red apples and strawberries are abundant." },
      { who: 'potato',  ko: "\"치즈 씨! 마침 저도 과일을 사러 왔어요.\"", en: "\"Cheese! I happened to come to buy fruits too.\"" },
      { who: 'cheese',  ko: "\"사과가 아주 크고 빨개요. 딸기도 참 싱싱해요.\"", en: "\"The apples are very big and red. The strawberries are so fresh too.\"" },
      { who: 'n',       ko: "가게 아저씨가 잘 익은 사과 한 조각을 건네요.", en: "The shopkeeper hands over a slice of well-ripened apple." },
      { who: 'potato',  ko: "\"와, 정말 달아요! 사과 네 개 주세요.\"", en: "\"Wow, it is really sweet! Please give us four apples.\"" },
      { who: 'n',       ko: "두 친구는 바구니에 과일을 담고 웃으며 돌아와요.", en: "The two friends put the fruits in the basket and return with smiles." },
    ],
    words: [
      { ko: "바구니", en: "basket" },
      { ko: "간식", en: "snack" },
      { ko: "딸기", en: "strawberry" },
      { ko: "사과", en: "apple" },
      { ko: "건네다", en: "to hand over" },
      { ko: "달다", en: "to be sweet" },
    ],
    quiz: [
      { q: { ko: "두 친구는 과일 가게에서 무엇을 샀어요?", en: "What did the two friends buy at the fruit store?" },
        options: ["바나나", "포도", "사과", "수박"], answer: 2 },
      { q: { ko: "가게 아저씨가 맛보라고 건넨 것은 무엇이에요?", en: "What did the shopkeeper hand over to taste?" },
        options: ["사과 한 조각", "딸기 한 개", "빵 한 조각", "사탕 하나"], answer: 0 },
    ],
  },
  {
    id: 'sb-16', lv: 1,
    title: { ko: "공원의 시원한 바람", en: "Cool Breeze in the Park" },
    blurb: { ko: "더운 날 공원 큰 나무 그늘 아래에서 쉬어요.", en: "Resting under the big tree shade in the park on a hot day." },
    pages: [
      { who: 'n',       ko: "햇볕이 쨍쨍해요. 오후가 되자 날씨가 더워요.", en: "The sun is blazing. In the afternoon the weather gets hot." },
      { who: 'cheese',  ko: "\"방 안이 조금 더워요. 시원한 곳에 가고 싶어요.\"", en: "\"Inside the room is a bit warm. I want to go somewhere cool.\"" },
      { who: 'potato',  ko: "\"우리 공원 큰 느티나무 그늘로 산책을 가요.\"", en: "\"Let's go for a walk to the shade of the big zelkova tree in the park.\"" },
      { who: 'n',       ko: "두 친구는 부채를 들고 공원으로 천천히 걸어가요.", en: "The two friends slowly walk to the park holding hand fans." },
      { who: 'n',       ko: "공원 나무 밑 벤치에 시원한 그늘이 넓게 드리워요.", en: "Under the park tree bench, cool shade spreads wide." },
      { who: 'cheese',  ko: "\"와, 바람이 솔솔 불어요! 정말 시원해요.\"", en: "\"Wow, the breeze blows gently! It is so cool.\"" },
      { who: 'potato',  ko: "\"초록 나뭇잎 소리도 듣기 좋아요. 눈을 감아 보세요.\"", en: "\"The sound of green leaves is nice to hear too. Please close your eyes.\"" },
      { who: 'n',       ko: "감자와 치즈는 벤치에 나란히 앉아 편안하게 쉬어요.", en: "Potato and Cheese sit side by side on the bench and rest comfortably." },
    ],
    words: [
      { ko: "더위", en: "heat" },
      { ko: "그늘", en: "shade" },
      { ko: "부채", en: "hand fan" },
      { ko: "벤치", en: "bench" },
      { ko: "나뭇잎", en: "tree leaf" },
      { ko: "편안하다", en: "to be comfortable" },
    ],
    quiz: [
      { q: { ko: "두 친구는 더위를 피해 어디로 갔어요?", en: "Where did the two friends go to escape the heat?" },
        options: ["도서관", "공원 나무 그늘", "식당 안", "지하철역"], answer: 1 },
      { q: { ko: "두 사람이 손에 들고 간 것은 무엇이에요?", en: "What did the two people hold in their hands?" },
        options: ["부채", "책", "물병", "우산"], answer: 0 },
    ],
  },
  {
    id: 'sb-17', lv: 2,
    title: { ko: "주말의 마트 장보기", en: "Weekend Supermarket Grocery Shopping" },
    blurb: { ko: "맛있는 저녁을 만들기 위해 마트에서 장을 봐요.", en: "Shopping for groceries at the supermarket to make a delicious dinner." },
    pages: [
      { who: 'n',       ko: "토요일 오후에 감자와 치즈는 장바구니를 챙겨 마트에 갔어요.", en: "On Saturday afternoon, Potato and Cheese took shopping bags and went to the mart." },
      { who: 'potato',  ko: "\"오늘 저녁에는 따뜻하고 맛있는 감자 수프를 끓일 거예요.\"", en: "\"Tonight I am going to cook warm and delicious potato soup.\"" },
      { who: 'cheese',  ko: "\"좋아요! 그럼 당근과 양파, 그리고 신선한 우유도 사야 해요.\"", en: "\"Great! Then we also need to buy carrots, onions, and fresh milk.\"" },
      { who: 'n',       ko: "두 친구는 채소 코너로 가서 싱싱한 당근과 흙 묻은 감자를 골랐어요.", en: "The two friends went to the vegetable section and picked fresh carrots and earthy potatoes." },
      { who: 'cheese',  ko: "\"이 감자는 단단하고 좋은데, 가격도 생각보다 아주 싸요.\"", en: "\"These potatoes are firm and good, and the price is cheaper than expected.\"" },
      { who: 'potato',  ko: "\"옆에 있는 고소한 버터도 하나 바구니에 담을게요.\"", en: "\"I will also put a block of savory butter next to it into the basket.\"" },
      { who: 'n',       ko: "필요한 재료를 모두 담은 후 계산대 앞에 줄을 섰어요.", en: "After putting all needed ingredients, they stood in line in front of the counter." },
      { who: 'cheese',  ko: "\"비닐봉투 대신 우리가 가져온 장바구니에 담으니까 참 뿌듯해요.\"", en: "\"Packing in our reusable bag instead of a plastic bag feels truly rewarding.\"" },
      { who: 'potato',  ko: "\"집에 가서 얼른 요리를 시작해요. 냄새만 맡아도 배가 고파요.\"", en: "\"Let's quickly start cooking at home. Just smelling it makes me hungry.\"" },
      { who: 'n',       ko: "두 친구는 장바구니를 사이좋게 나누어 들고 집으로 돌아왔어요.", en: "The two friends shared carrying the grocery bag and returned home happily." },
    ],
    words: [
      { ko: "장바구니", en: "grocery shopping bag" },
      { ko: "수프", en: "soup" },
      { ko: "당근", en: "carrot" },
      { ko: "단단하다", en: "to be firm, solid" },
      { ko: "버터", en: "butter" },
      { ko: "뿌듯하다", en: "to feel proud, fulfilled" },
    ],
    quiz: [
      { q: { ko: "두 친구가 저녁에 만들기로 한 요리는 무엇이에요?", en: "What dish did the two friends decide to make for dinner?" },
        options: ["된장찌개", "감자 수프", "과일 샐러드", "토마토 파스타"], answer: 1 },
      { q: { ko: "물건을 담을 때 비닐봉투 대신 무엇을 썼어요?", en: "What did they use instead of a plastic bag when packing items?" },
        options: ["종이 상자", "가져온 장바구니", "배낭", "천 보자기"], answer: 1 },
    ],
  },
  {
    id: 'sb-18', lv: 2,
    title: { ko: "치즈의 깜짝 생일 파티", en: "Cheese's Surprise Birthday Party" },
    blurb: { ko: "치즈의 생일을 축하하기 위해 감자가 선물을 준비해요.", en: "Potato prepares a gift to celebrate Cheese's birthday." },
    pages: [
      { who: 'n',       ko: "오늘은 치즈의 생일이지만, 치즈는 일 때문에 바빠서 잊고 있었어요.", en: "Today is Cheese's birthday, but Cheese was busy with work and had forgotten it." },
      { who: 'potato',  ko: "\"치즈 씨가 오기 전에 방을 예쁘게 꾸미고 케이크를 준비할 거예요.\"", en: "\"Before Cheese comes, I will decorate the room prettily and prepare a cake.\"" },
      { who: 'n',       ko: "감자는 동네 제과점에 들러 딸기가 얹힌 예쁜 케이크를 샀어요.", en: "Potato dropped by the neighborhood bakery and bought a pretty cake topped with strawberries." },
      { who: 'n',       ko: "벽에는 알록달록한 풍선을 달고 식탁 위에 촛불을 켰어요.", en: "Potato hung colorful balloons on the wall and lit candles on the table." },
      { who: 'n',       ko: "저녁 일곱 시에 문이 열리고 피곤한 얼굴의 치즈가 들어왔어요.", en: "At seven in the evening, the door opened and Cheese entered with a tired face." },
      { who: 'potato',  ko: "\"치즈 씨, 생일 축하해요! 이 작은 선물도 받으세요.\"", en: "\"Happy birthday, Cheese! Please receive this small gift too.\"" },
      { who: 'cheese',  ko: "\"어머나, 제 생일을 기억해 주었군요! 정말 감동받았어요.\"", en: "\"Oh my, you remembered my birthday! I am so touched.\"" },
      { who: 'n',       ko: "치즈는 촛불을 불어 끄며 마음속으로 소원을 빌었어요.", en: "Cheese blew out the candles and made a wish in the heart." },
      { who: 'cheese',  ko: "\"피곤이 한순간에 다 사라졌어요. 감자 씨, 고마워요!\"", en: "\"My fatigue vanished in an instant. Thank you, Potato!\"" },
      { who: 'n',       ko: "두 친구는 달콤한 케이크를 나누어 먹으며 즐거운 밤을 보냈어요.", en: "The two friends shared the sweet cake and spent an enjoyable evening." },
    ],
    words: [
      { ko: "생일", en: "birthday" },
      { ko: "제과점", en: "bakery" },
      { ko: "풍선", en: "balloon" },
      { ko: "촛불", en: "candlelight" },
      { ko: "감동", en: "deep impression, moved" },
      { ko: "소원", en: "wish" },
    ],
    quiz: [
      { q: { ko: "감자가 제과점에서 사 온 것은 무엇이에요?", en: "What did Potato buy from the bakery?" },
        options: ["딸기 케이크", "단팥빵", "샌드위치", "쿠키 상자"], answer: 0 },
      { q: { ko: "치즈는 촛불을 끄면서 무엇을 했어요?", en: "What did Cheese do while blowing out the candles?" },
        options: ["노래를 불렀어요", "선물을 열었어요", "소원을 빌었어요", "창문을 열었어요"], answer: 2 },
    ],
  },
  {
    id: 'sb-19', lv: 2,
    title: { ko: "자전거를 달리는 일요일", en: "Riding Bicycles on Sunday" },
    blurb: { ko: "일요일 아침 강변길을 따라 자전거를 달려요.", en: "Riding bicycles along the riverside path on Sunday morning." },
    pages: [
      { who: 'n',       ko: "일요일 아침 공기가 상쾌해서 감자는 자전거를 꺼냈어요.", en: "Because the Sunday morning air was fresh, Potato took out the bicycle." },
      { who: 'potato',  ko: "\"치즈 씨, 오늘 날씨가 참 좋은데 강변길로 자전거 타러 갈래요?\"", en: "\"Cheese, the weather is so nice today, do you want to ride bikes along the river?\"" },
      { who: 'cheese',  ko: "\"오랜만에 타서 조금 떨리지만, 천천히 달리면 괜찮을 거예요.\"", en: "\"I am a bit nervous since it's been a while, but if we pedal slowly it'll be fine.\"" },
      { who: 'n',       ko: "두 친구는 안전모를 단단히 쓰고 자전거 도로로 출발했어요.", en: "The two friends put on helmets securely and set off onto the bicycle lane." },
      { who: 'n',       ko: "강가에는 코스모스 꽃이 활짝 피어 있고 시원한 강바람이 불었어요.", en: "By the river, cosmos flowers were in full bloom and a cool river breeze blew." },
      { who: 'cheese',  ko: "\"바람을 가르며 달리니까 마음속 걱정이 모두 날아가는 것 같아요.\"", en: "\"Riding through the breeze feels like all worries in my mind blow away.\"" },
      { who: 'potato',  ko: "\"저기 앞 정자에서 시원한 보리차를 마시며 잠시 쉬어가요.\"", en: "\"Let's take a short rest at that pavilion ahead while drinking cool barley tea.\"" },
      { who: 'n',       ko: "두 사람은 자전거를 세워 두고 그늘 밑 벤치에 앉았어요.", en: "The two parked their bicycles and sat on the bench under the shade." },
      { who: 'cheese',  ko: "\"다음 주말에도 날씨가 맑으면 또 자전거를 타러 오고 싶어요.\"", en: "\"If the weather is clear next weekend too, I want to come ride bicycles again.\"" },
      { who: 'n',       ko: "두 친구는 보리차를 나누어 마신 뒤 가벼운 발걸음으로 페달을 밟았어요.", en: "After sharing barley tea, the two friends pedaled with light steps." },
    ],
    words: [
      { ko: "상쾌하다", en: "to be refreshing" },
      { ko: "안전모", en: "helmet" },
      { ko: "강변", en: "riverside" },
      { ko: "보리차", en: "barley tea" },
      { ko: "페달", en: "pedal" },
      { ko: "세우다", en: "to park, stop" },
    ],
    quiz: [
      { q: { ko: "두 친구가 자전거를 탄 곳은 어디예요?", en: "Where did the two friends ride their bicycles?" },
        options: ["산길", "강변길", "복잡한 시장", "학교 운동장"], answer: 1 },
      { q: { ko: "정자에서 쉬면서 마신 음료는 무엇이에요?", en: "What drink did they drink while resting at the pavilion?" },
        options: ["커피", "주스", "보리차", "우유"], answer: 2 },
    ],
  },
  {
    id: 'sb-20', lv: 2,
    title: { ko: "도서관에서 빌린 책", en: "Books Borrowed from the Library" },
    blurb: { ko: "조용한 도서관에서 읽고 싶은 책을 찾아요.", en: "Finding books to read in the quiet library." },
    pages: [
      { who: 'n',       ko: "비가 부슬부슬 내리는 날, 감자와 치즈는 동네 도서관으로 향했어요.", en: "On a drizzly day, Potato and Cheese headed to the neighborhood library." },
      { who: 'potato',  ko: "\"빗소리를 들으며 조용히 책을 읽으면 마음이 참 차분해져요.\"", en: "\"Listening to the sound of rain while reading quietly makes the heart so calm.\"" },
      { who: 'n',       ko: "도서관 안은 아주 조용했고 종이 냄새가 은은하게 났어요.", en: "Inside the library was very quiet and smelled faintly of paper." },
      { who: 'cheese',  ko: "\"저는 한국 전통 음식에 관한 그림책을 찾고 싶어요.\"", en: "\"I want to find a picture book about traditional Korean food.\"" },
      { who: 'n',       ko: "컴퓨터로 책 위치를 검색한 뒤 서가 사이를 조심조심 걸었어요.", en: "After searching the book's location on the computer, they walked carefully between shelves." },
      { who: 'potato',  ko: "\"치즈 씨, 여기 두 번째 칸에 찾던 요리책이 꽂혀 있어요!\"", en: "\"Cheese, the cookbook you were looking for is on this second shelf!\"" },
      { who: 'cheese',  ko: "\"고마워요! 감자 씨는 어떤 책을 읽을 거예요?\"", en: "\"Thank you! What kind of book are you going to read, Potato?\"" },
      { who: 'potato',  ko: "\"저는 아름다운 한국 여행지 사진이 담긴 책을 골랐어요.\"", en: "\"I picked a book containing photos of beautiful Korean travel destinations.\"" },
      { who: 'n',       ko: "두 친구는 창가 책상에 나란히 앉아 두 시간 동안 책에 푹 빠졌어요.", en: "The two friends sat side by side at the window desk and were absorbed in books for two hours." },
      { who: 'n',       ko: "나오는 길에 대출 카드를 보여주고 책을 두 권씩 빌려왔어요.", en: "On the way out, they showed library cards and borrowed two books each." },
    ],
    words: [
      { ko: "도서관", en: "library" },
      { ko: "차분하다", en: "to be calm" },
      { ko: "검색하다", en: "to search" },
      { ko: "서가", en: "bookshelf, stacks" },
      { ko: "여행지", en: "travel destination" },
      { ko: "대출", en: "lending, checkout" },
    ],
    quiz: [
      { q: { ko: "치즈가 도서관에서 찾은 책은 무엇에 관한 책이에요?", en: "What was the book Cheese looked for in the library about?" },
        options: ["한국 전통 음식", "세계 역사", "외국어 공부", "과학 이야기"], answer: 0 },
      { q: { ko: "두 친구는 각자 책을 몇 권씩 빌렸어요?", en: "How many books did each friend borrow?" },
        options: ["한 권씩", "두 권씩", "세 권씩", "네 권씩"], answer: 1 },
    ],
  },
  {
    id: 'sb-21', lv: 2,
    title: { ko: "동네 빨래방 이야기", en: "Neighborhood Laundromat Story" },
    blurb: { ko: "두꺼운 겨울 이불을 빨래방에서 깨끗이 빨아요.", en: "Washing thick winter blankets clean at the laundromat." },
    pages: [
      { who: 'n',       ko: "겨울이 지나고 따뜻한 봄이 오자 감자는 두꺼운 이불을 꺼냈어요.", en: "When winter passed and warm spring arrived, Potato took out thick blankets." },
      { who: 'potato',  ko: "\"집 세탁기는 작아서 큰 이불을 빨 수 없어요. 빨래방에 가야겠어요.\"", en: "\"The home washing machine is small and cannot wash large blankets. I must go to the laundromat.\"" },
      { who: 'cheese',  ko: "\"저도 베개 커버를 빨아야 하니까 같이 가요.\"", en: "\"I also need to wash pillow covers, so let's go together.\"" },
      { who: 'n',       ko: "두 사람은 커다란 보따리를 들고 동네 빨래방으로 걸어갔어요.", en: "The two carried a big bundle and walked to the neighborhood laundromat." },
      { who: 'n',       ko: "빨래방 안에는 대형 세탁기가 윙윙 소리를 내며 돌아가고 있었어요.", en: "Inside the laundromat, large washing machines were running with whirring sounds." },
      { who: 'potato',  ko: "\"동전을 넣고 세제를 부으면 세탁이 저절로 시작돼요.\"", en: "\"If we insert coins and pour detergent, washing starts automatically.\"" },
      { who: 'n',       ko: "빨래가 돌아가는 동안 두 친구는 의자에 앉아 만화책을 읽었어요.", en: "While laundry spun, the two friends sat on chairs and read comic books." },
      { who: 'cheese',  ko: "\"건조기까지 돌리니까 이불이 뽀송뽀송하고 정말 따뜻해요.\"", en: "\"After running the dryer too, the blanket is fluffy and really warm.\"" },
      { who: 'potato',  ko: "\"햇볕 냄새가 솔솔 나는 것 같아요. 오늘 밤에는 꿀잠을 잘 거예요.\"", en: "\"It feels like sunny scents blow softly. Tonight I will sleep like a log.\"" },
      { who: 'n',       ko: "향긋한 이불을 품에 안고 두 친구는 기분 좋게 빨래방을 나섰어요.", en: "Embracing the fragrant blanket in arms, the two friends left the laundromat cheerfully." },
    ],
    words: [
      { ko: "빨래방", en: "laundromat" },
      { ko: "이불", en: "blanket" },
      { ko: "보따리", en: "bundle, pack" },
      { ko: "세제", en: "detergent" },
      { ko: "건조기", en: "dryer" },
      { ko: "뽀송뽀송하다", en: "to be soft and dry" },
    ],
    quiz: [
      { q: { ko: "감자가 빨래방에 간 까닭은 무엇이에요?", en: "Why did Potato go to the laundromat?" },
        options: ["운동화를 빨려고", "큰 이불을 빨려고", "외투를 사려고", "친구를 만나려고"], answer: 1 },
      { q: { ko: "빨래가 돌아가는 동안 두 사람은 무엇을 했어요?", en: "What did the two people do while the laundry was running?" },
        options: ["잠을 잤어요", "밥을 먹었어요", "만화책을 읽었어요", "운동을 했어요"], answer: 2 },
    ],
  },
  {
    id: 'sb-22', lv: 2,
    title: { ko: "비 오는 날의 부침개", en: "Korean Pancakes on a Rainy Day" },
    blurb: { ko: "빗소리를 들으며 바삭한 부침개를 부쳐 먹어요.", en: "Frying and eating crispy savory pancakes while listening to the rain." },
    pages: [
      { who: 'n',       ko: "아침부터 하늘이 어둡더니 점심때가 되자 굵은 빗방울이 떨어졌어요.", en: "The sky was dark since morning, and around lunch thick raindrops fell." },
      { who: 'cheese',  ko: "\"빗소리가 꼭 기름에 지글지글 전을 부치는 소리 같아요.\"", en: "\"The sound of rain sounds just like sizzling pancakes in oil.\"" },
      { who: 'potato',  ko: "\"맞아요! 한국에서는 비 오는 날에 부침개를 자주 부쳐 먹는대요.\"", en: "\"That's right! They say people often fry savory pancakes on rainy days in Korea.\"" },
      { who: 'cheese',  ko: "\"우리 냉장고에 남은 파와 김치가 있으니까 얼른 만들어 봐요.\"", en: "\"We have green onions and kimchi left in the fridge, so let's make some quickly.\"" },
      { who: 'n',       ko: "감자는 부침가루에 시원한 물을 부어 반죽을 걸쭉하게 만들었어요.", en: "Potato poured cold water into pancake powder and made thick batter." },
      { who: 'cheese',  ko: "\"잘 익은 김치를 잘게 썰어서 반죽에 넣을게요.\"", en: "\"I will finely chop well-ripened kimchi and put it into the batter.\"" },
      { who: 'n',       ko: "달군 프라이팬에 기름을 넉넉히 두르고 반죽을 얇게 폈어요.", en: "They poured plenty of oil on the heated frying pan and spread the batter thinly." },
      { who: 'potato',  ko: "\"겉은 바삭하고 속은 촉촉하게 잘 익었어요. 타지 않게 뒤집을게요.\"", en: "\"The outside is crispy and inside is moist. I'll flip so it doesn't burn.\"" },
      { who: 'cheese',  ko: "\"간장에 식초를 조금 넣은 양념장에 찍어 먹으니까 정말 꿀맛이에요.\"", en: "\"Dipping it into soy sauce with a dash of vinegar tastes heavenly.\"" },
      { who: 'n',       ko: "창밖에는 비가 내렸지만 방 안은 고소한 냄새와 웃음으로 가득했어요.", en: "Outside the window rain fell, but inside the room was filled with savory scents and laughter." },
    ],
    words: [
      { ko: "빗방울", en: "raindrop" },
      { ko: "부침개", en: "Korean savory pancake" },
      { ko: "반죽", en: "batter, dough" },
      { ko: "바삭하다", en: "to be crispy" },
      { ko: "촉촉하다", en: "to be moist" },
      { ko: "양념장", en: "seasoned sauce" },
    ],
    quiz: [
      { q: { ko: "두 친구가 비 오는 날 만들어 먹은 음식은 무엇이에요?", en: "What food did the two friends make and eat on a rainy day?" },
        options: ["라면", "김밥", "부침개", "떡볶이"], answer: 2 },
      { q: { ko: "반죽에 넣은 주재료는 무엇이에요?", en: "What was the main ingredient put into the batter?" },
        options: ["소고기", "김치와 파", "감자와 당근", "해물과 치즈"], answer: 1 },
    ],
  },
  {
    id: 'sb-23', lv: 3,
    title: { ko: "골목길에서 길을 잃은 날", en: "The Day We Got Lost in an Alley" },
    blurb: { ko: "낯선 골목길에서 지도를 보며 오래된 찻집을 찾아요.", en: "Looking for an old teahouse with a map in an unfamiliar alley." },
    pages: [
      { who: 'n',       ko: "주말 오후, 감자와 치즈는 소문난 전통 찻집을 찾아 오래된 동네 골목길로 들어섰습니다.", en: "On a weekend afternoon, Potato and Cheese entered an old neighborhood alley to find a famous traditional teahouse." },
      { who: 'potato',  ko: "\"지도 앱에는 이 골목 끝에 찻집이 있다고 나오는데, 아무리 둘러봐도 간판이 안 보여요.\"", en: "\"The map app says the teahouse is at the end of this alley, but no matter how I look around I cannot see the sign.\"" },
      { who: 'cheese',  ko: "\"골목이 좁고 갈림길이 많아서 길을 잘못 든 것 같아요. 지나가는 분께 여쭤볼까요?\"", en: "\"The alleys are narrow with many forks, so it seems we took the wrong turn. Shall we ask someone passing by?\"" },
      { who: 'n',       ko: "마침 근처 한옥 대문 앞에서 화분에 물을 주시던 인자한 할아버지 한 분이 보였습니다.", en: "Just then, a gentle grandfather watering flowerpots in front of a hanok gate was seen." },
      { who: 'potato',  ko: "\"어르신, 실례지만 솔향 찻집에 가려면 어느 쪽으로 걸어가야 하나요?\"", en: "\"Sir, excuse me, but which way should we walk to get to the Solhyang Teahouse?\"" },
      { who: 'n',       ko: "할아버지는 허허 웃으시며 손을 들어 골목 안쪽을 가리키셨습니다. \"여기서 왼쪽 담장을 끼고 돌면 바로 나와요.\"", en: "The grandfather chuckled and pointed inside the alley: \"If you turn along the left wall from here, it comes right out.\"" },
      { who: 'cheese',  ko: "\"정말 친절하게 알려 주셔서 감사합니다. 좋은 하루 보내세요, 어르신!\"", en: "\"Thank you so much for guiding us kindly. Have a wonderful day, sir!\"" },
      { who: 'n',       ko: "할아버지가 일러주신 대로 기와 담장을 돌아가니 아담한 나무 간판이 걸린 찻집이 나타났습니다.", en: "Following the grandfather's directions around the tiled wall, a cozy teahouse with a wooden sign appeared." },
      { who: 'potato',  ko: "\"길을 헤맬 때는 스마트폰 지도보다 동네 어르신의 한마디가 훨씬 더 정확하네요.\"", en: "\"When wandering off, a local elder's word is much more accurate than a smartphone map.\"" },
      { who: 'cheese',  ko: "\"찻집 마당에 모과나무가 참 예뻐요. 따뜻한 대추차를 마시며 여유를 즐겨요.\"", en: "\"The quince tree in the teahouse yard is so pretty. Let's enjoy leisure drinking warm jujube tea.\"" },
      { who: 'n',       ko: "찻잔에서 피어오르는 달콤한 향기를 맡으며 두 친구는 골목길 산책의 매력에 푹 빠졌습니다.", en: "Smelling the sweet scent rising from the teacup, the two friends fell deeply in love with alley walking." },
      { who: 'potato',  ko: "\"다음 주말에도 새로운 골목길을 천천히 걸어보고 싶어요. 오늘 길을 잃은 덕분에 좋은 곳을 알게 되었어요.\"", en: "\"I want to slowly walk down a new alley next weekend too. Thanks to getting lost today, we discovered a great place.\"" },
    ],
    words: [
      { ko: "갈림길", en: "fork in the road" },
      { ko: "간판", en: "signboard" },
      { ko: "어르신", en: "elder (honorific)" },
      { ko: "헤매다", en: "to wander, lose one's way" },
      { ko: "여유", en: "leisure, composure" },
      { ko: "피어오르다", en: "to rise, waft" },
    ],
    quiz: [
      { q: { ko: "두 친구가 찾으려고 한 곳은 어디예요?", en: "Where were the two friends trying to find?" },
        options: ["전통 찻집", "동네 도서관", "우체국", "사진관"], answer: 0 },
      { q: { ko: "찻집으로 가는 길을 친절하게 알려 준 사람은 누구예요?", en: "Who kindly guided the way to the teahouse?" },
        options: ["경찰관", "꽃집 사장님", "동네 할아버지", "버스 기사"], answer: 2 },
    ],
  },
  {
    id: 'sb-24', lv: 3,
    title: { ko: "감기가 찾아온 날", en: "The Day a Cold Visited" },
    blurb: { ko: "감기에 걸린 치즈를 위해 감자가 따뜻한 죽을 끓여요.", en: "Potato cooks warm porridge for Cheese who caught a cold." },
    pages: [
      { who: 'n',       ko: "아침부터 쌀쌀한 바람이 불더니 치즈가 목이 따갑고 기침을 콜록콜록하기 시작했습니다.", en: "Chilly wind blew since morning, and Cheese began having a sore throat and coughing." },
      { who: 'cheese',  ko: "\"이마에 열도 조금 있는 것 같고 온몸이 으슬으슬 떨려요.\"", en: "\"I think my forehead has a fever too, and my whole body is shivering with chills.\"" },
      { who: 'potato',  ko: "\"환절기 감기에 걸린 모양이에요. 무리하지 말고 오늘은 푹 쉬어야 해요.\"", en: "\"It looks like you caught a seasonal cold. Do not overwork, and you must rest thoroughly today.\"" },
      { who: 'n',       ko: "감자는 약국에 뛰어가서 기침약과 종합 감기약을 사 왔습니다.", en: "Potato ran to the pharmacy and bought cough medicine and comprehensive cold medicine." },
      { who: 'potato',  ko: "\"약을 먹기 전에 빈속을 채워야 하니까 제가 부드러운 야채죽을 끓여 올게요.\"", en: "\"You need to fill an empty stomach before taking medicine, so I will cook and bring soft vegetable porridge.\"" },
      { who: 'n',       ko: "감자는 주방에서 냄비에 밥과 잘게 썬 호박, 당근을 넣고 정성스럽게 저었습니다.", en: "In the kitchen, Potato put rice, finely chopped zucchini and carrots into a pot, stirring devotedly." },
      { who: 'n',       ko: "고소한 참기름 냄새가 방 안 가득 퍼지자 치즈가 힘겹게 몸을 일으켰습니다.", en: "As the savory smell of sesame oil filled the room, Cheese weakly raised the body." },
      { who: 'cheese',  ko: "\"감자 씨 덕분에 따뜻한 죽을 먹으니까 벌써 기운이 조금 나는 것 같아요.\"", en: "\"Thanks to Potato, eating warm porridge makes me feel like my energy is returning already.\"" },
      { who: 'potato',  ko: "\"약 드신 후에 두꺼운 이불 덮고 한숨 푹 주무세요. 설거지는 제가 할게요.\"", en: "\"After taking medicine, cover with a thick blanket and sleep soundly. I will do the dishes.\"" },
      { who: 'n',       ko: "치즈는 감자의 다정한 보살핌 속에서 약을 먹고 깊은 잠에 빠져들었습니다.", en: "Under Potato's affectionate care, Cheese took medicine and fell into a deep sleep." },
      { who: 'cheese',  ko: "\"저녁이 되니 열이 싹 내렸어요. 곁에서 챙겨줘서 정말 고마워요.\"", en: "\"By evening the fever completely went down. Thank you so much for taking care of me beside me.\"" },
      { who: 'potato',  ko: "\"이웃끼리는 서로 돕고 사는 법이지요. 푹 나을 때까지 푹 쉬세요.\"", en: "\"Neighbors are meant to live helping each other. Please rest until completely healed.\"" },
    ],
    words: [
      { ko: "기침", en: "cough" },
      { ko: "으슬으슬하다", en: "to feel chilly, shiver" },
      { ko: "환절기", en: "change of seasons" },
      { ko: "야채죽", en: "vegetable porridge" },
      { ko: "참기름", en: "sesame oil" },
      { ko: "보살핌", en: "care, attention" },
    ],
    quiz: [
      { q: { ko: "치즈가 아플 때 감자가 만들어 준 음식은 무엇이에요?", en: "What food did Potato make when Cheese was sick?" },
        options: ["미역국", "야채죽", "김치찌개", "샌드위치"], answer: 1 },
      { q: { ko: "감자가 약국에서 사 온 것은 무엇이에요?", en: "What did Potato buy from the pharmacy?" },
        options: ["반창고", "비타민 음료", "감기약", "안약"], answer: 2 },
    ],
  },
  {
    id: 'sb-25', lv: 3,
    title: { ko: "새 이웃에게 건넨 떡", en: "Rice Cakes Given to a New Neighbor" },
    blurb: { ko: "옆집에 새로 이사 온 이웃에게 이사 떡을 나누어요.", en: "Sharing moving rice cakes with a neighbor who recently moved next door." },
    pages: [
      { who: 'n',       ko: "오전 내내 옆집 복도에서 짐 옮기는 소리가 분주하게 들려왔습니다.", en: "All morning, the busy sound of moving luggage was heard in the hallway next door." },
      { who: 'cheese',  ko: "\"옆집에 새로운 이웃이 이사를 온 모양이에요. 사다리차가 큰 짐을 올리고 있어요.\"", en: "\"It looks like a new neighbor moved in next door. A ladder truck is lifting big furniture.\"" },
      { who: 'potato',  ko: "\"한국에서는 이사를 오거나 가면 이웃에게 팥떡을 돌리는 풍습이 있잖아요.\"", en: "\"In Korea, there is a custom of sharing red bean rice cakes with neighbors when moving in or out.\"" },
      { who: 'n',       ko: "두 친구는 동네 떡집에 들러 갓 쪄낸 따끈따끈한 시루떡 한 상자를 사 왔습니다.", en: "The two friends dropped by the neighborhood rice cake shop and bought a box of freshly steamed warm sirutteok." },
      { who: 'n',       ko: "접시에 예쁘게 떡을 담고 랩을 씌운 뒤 옆집 초인종을 조심스럽게 눌렀습니다.", en: "After placing the rice cakes neatly on a plate and wrapping them, they gently pressed the next-door doorbell." },
      { who: 'n',       ko: "문이 열리고 이삿짐 정리에 땀을 흘리던 젊은 청년이 고개를 내밀었습니다. \"누구세요?\"", en: "The door opened and a young man sweating from organizing moving boxes peeked out: \"Who is it?\"" },
      { who: 'potato',  ko: "\"안녕하세요! 옆집 301호 주민들인데, 이사 축하드리려고 작은 떡을 가져왔어요.\"", en: "\"Hello! We are the residents from room 301 next door, and we brought some small rice cakes to congratulate your move.\"" },
      { who: 'n',       ko: "청년은 깜짝 놀라며 환한 미소를 지었습니다. \"와, 정말 감사합니다! 짐 정리하느라 점심도 못 먹었는데 큰 힘이 되네요.\"", en: "The young man was surprised and showed a bright smile: \"Wow, thank you so much! I couldn't even eat lunch organizing luggage, this gives me great strength.\"" },
      { who: 'cheese',  ko: "\"필요한 공구나 도움이 있으면 언제든 편하게 문을 두드리세요.\"", en: "\"If you ever need tools or help, feel free to knock on our door anytime.\"" },
      { who: 'n',       ko: "청년은 고마워하며 배웅했고, 복도에는 이웃 간의 훈훈한 정이 가득 찼습니다.", en: "The young man expressed gratitude and saw them off, and the hallway was filled with warm neighborly affection." },
      { who: 'potato',  ko: "\"작은 떡 한 접시로 새 이웃과 반갑게 인사할 수 있어서 참 보람차네요.\"", en: "\"Being able to greet our new neighbor warmly with a small plate of rice cakes is truly rewarding.\"" },
      { who: 'cheese',  ko: "\"앞으로 오며 가며 마주칠 때마다 반갑게 인사하며 지내야겠어요.\"", en: "\"Whenever we run into each other coming and going, we should greet each other warmly.\"" },
    ],
    words: [
      { ko: "이사", en: "moving (house)" },
      { ko: "사다리차", en: "ladder truck" },
      { ko: "시루떡", en: "steamed red bean rice cake" },
      { ko: "초인종", en: "doorbell" },
      { ko: "환하다", en: "to be bright" },
      { ko: "정", en: "affection, bond" },
    ],
    quiz: [
      { q: { ko: "두 친구가 새 이웃에게 건넨 선물은 무엇이에요?", en: "What gift did the two friends give to the new neighbor?" },
        options: ["과일 바구니", "따뜻한 시루떡", "꽃 화분", "음료수 한 박스"], answer: 1 },
      { q: { ko: "새 이웃 청년이 문을 열었을 때 어떤 상태였어요?", en: "In what state was the young new neighbor when opening the door?" },
        options: ["밥을 먹고 있었어요", "책을 읽고 있었어요", "짐 정리로 땀을 흘리고 있었어요", "잠을 자고 있었어요"], answer: 2 },
    ],
  },
  {
    id: 'sb-26', lv: 3,
    title: { ko: "비 오는 날의 분실물", en: "Lost Property on a Rainy Day" },
    blurb: { ko: "지하철 승강장에 두고 온 가방을 분실물 센터에서 찾아요.", en: "Finding a bag left on the subway platform at the lost and found center." },
    pages: [
      { who: 'n',       ko: "비가 세차게 쏟아지던 저녁, 감자는 지하철에서 내리다가 중요한 서류 가방을 두고 내렸습니다.", en: "On a rainy evening, Potato got off the subway leaving behind an important document bag." },
      { who: 'potato',  ko: "\"치즈 씨, 큰일 났어요! 방금 타고 온 지하철 선반 위에 제 가방을 놓고 내렸어요.\"", en: "\"Cheese, big trouble! I left my bag on the overhead shelf of the subway I just rode.\"" },
      { who: 'cheese',  ko: "\"당황하지 말고 침착하게 생각해요. 몇 시에 탄 몇 호선 열차였는지 기억나요?\"", en: "\"Don't panic and think calmly. Do you remember what line and what time train you rode?\"" },
      { who: 'potato',  ko: "\"오후 여섯 시 십 분에 시청역에서 탄 2호선 열차였어요. 세 번째 칸이었고요.\"", en: "\"It was a Line 2 train boarded at City Hall Station at 6:10 PM. In the third car.\"" },
      { who: 'cheese',  ko: "\"열차 번호와 시간을 알면 찾을 수 있어요. 역무실로 얼른 가 봐요.\"", en: "\"If you know the train number and time, we can find it. Let's quickly go to the station office.\"" },
      { who: 'n',       ko: "두 친구는 개찰구 옆 고객안전실로 뛰어가 역무원에게 분실물 사정을 설명했습니다.", en: "The two friends ran to the customer safety room beside the turnstile and explained the lost item situation to the attendant." },
      { who: 'n',       ko: "역무원은 친절하게 종착역에 무전을 연결했습니다. \"남색 서류 가방이 보관되어 있다고 하네요.\"", en: "The station attendant kindly radioed the terminal station: \"They say a navy document bag has been secured.\"" },
      { who: 'potato',  ko: "\"정말 다행이에요! 그 안에 소중한 스케치북과 필통이 들어 있거든요.\"", en: "\"What a huge relief! Inside are my precious sketchbook and pencil case.\"" },
      { who: 'cheese',  ko: "\"종착역 분실물 센터로 가면 가방을 바로 찾아올 수 있대요.\"", en: "\"They say if we go to the lost and found at the terminal station, we can retrieve the bag right away.\"" },
      { who: 'n',       ko: "두 친구는 다음 열차를 타고 종착역으로 가 신분증을 확인하고 가방을 무사히 돌려받았습니다.", en: "The two friends took the next train to the terminal station, checked ID, and safely received the bag back." },
      { who: 'potato',  ko: "\"친절하게 도와주신 역무원님 덕분에 찾을 수 있었어요. 앞으로는 내리기 전에 꼭 확인해야겠어요.\"", en: "\"Thanks to the kind station attendant, I was able to find it. In the future I must double-check before getting off.\"" },
      { who: 'cheese',  ko: "\"맞아요. 비 오는 날에는 짐을 챙기느라 정신이 없으니까 특히 조심해야 해요.\"", en: "\"Right. On rainy days one is flustered taking care of belongings, so one must be especially careful.\"" },
    ],
    words: [
      { ko: "분실물", en: "lost property, lost item" },
      { ko: "선반", en: "overhead shelf" },
      { ko: "역무원", en: "station attendant" },
      { ko: "종착역", en: "terminal station" },
      { ko: "신분증", en: "ID card" },
      { ko: "정신없다", en: "to be hectic, distracted" },
    ],
    quiz: [
      { q: { ko: "감자가 지하철에 두고 내린 물건은 무엇이에요?", en: "What item did Potato leave behind on the subway?" },
        options: ["우산", "스마트폰", "남색 서류 가방", "지갑"], answer: 2 },
      { q: { ko: "분실물을 찾기 위해 가장 먼저 찾아간 곳은 어디예요?", en: "Where did they visit first to locate the lost item?" },
        options: ["역무실 (고객안전실)", "경찰서", "편의점", "종착역"], answer: 0 },
    ],
  },
  {
    id: 'sb-27', lv: 3,
    title: { ko: "가을 산책과 따뜻한 호빵", en: "Autumn Walk and Steaming Buns" },
    blurb: { ko: "노란 은행잎 길을 걷고 편의점에서 김이 나는 호빵을 사 먹어요.", en: "Walking along golden ginkgo paths and eating steaming buns at the convenience store." },
    pages: [
      { who: 'n',       ko: "완연한 가을이 되어 동네 큰길가 은행나무들이 온통 노랗게 물들었습니다.", en: "With full autumn arrived, ginkgo trees along the neighborhood main avenue turned completely yellow." },
      { who: 'potato',  ko: "\"발밑에 노란 은행잎이 카펫처럼 깔려 있어요. 바스락거리는 소리가 듣기 좋아요.\"", en: "\"Yellow ginkgo leaves are spread like a carpet under our feet. The rustling sound is pleasant to hear.\"" },
      { who: 'cheese',  ko: "\"바람이 조금 쌀쌀하니까 외투 깃을 여미세요. 가을바람은 금방 차가워져요.\"", en: "\"The wind is a bit chilly, so tighten your coat collar. Autumn wind quickly grows cold.\"" },
      { who: 'n',       ko: "두 친구는 단풍을 감상하며 동네 산책로를 따라 오랫동안 걸었습니다.", en: "The two friends walked along the neighborhood trail for a long time admiring the autumn leaves." },
      { who: 'n',       ko: "산책을 마치고 돌아오는 길목, 편의점 유리창 너머로 김이 모락모락 나는 찜기가 보였습니다.", en: "On their way back after walking, beyond the convenience store window a steaming bun steamer was seen." },
      { who: 'cheese',  ko: "\"저기 찜기 안에 하얀 단팥 호빵과 야채 호빵이 나란히 놓여 있어요!\"", en: "\"Inside that steamer, white red bean buns and vegetable buns are placed side by side!\"" },
      { who: 'potato',  ko: "\"찬 바람을 맞으며 걷고 난 뒤에는 뜨거운 호빵만 한 간식이 없지요.\"", en: "\"After walking in cold winds, there is no snack quite like piping hot steamed buns.\"" },
      { who: 'n',       ko: "두 사람은 편의점에 들어가 갓 꺼낸 뜨끈한 호빵을 하나씩 샀습니다.", en: "The two entered the convenience store and bought freshly taken warm steamed buns each." },
      { who: 'potato',  ko: "\"호호 불어가며 반으로 가르니까 달콤한 단팥 소가 가득 들어 있어요.\"", en: "\"Blowing puff puff and splitting it in half, it is full of sweet red bean filling.\"" },
      { who: 'cheese',  ko: "\"손도 따뜻해지고 배도 든든해지네요. 가을의 맛이란 바로 이런 것 같아요.\"", en: "\"My hands get warm and my belly gets full. Autumn's flavor seems to be exactly this.\"" },
      { who: 'n',       ko: "두 친구는 편의점 앞 파라솔 의자에 앉아 노을 지는 하늘을 보며 호빵을 먹었습니다.", en: "The two friends sat on parasol chairs in front of the convenience store and ate buns watching the sunset sky." },
      { who: 'potato',  ko: "\"계절마다 이렇게 소박한 기쁨을 함께 나눌 수 있어서 매일이 행복해요.\"", en: "\"Being able to share such humble joys every season together makes every day happy.\"" },
    ],
    words: [
      { ko: "은행나무", en: "ginkgo tree" },
      { ko: "바스락거리다", en: "to rustle" },
      { ko: "호빵", en: "steamed stuffed bun" },
      { ko: "찜기", en: "steamer" },
      { ko: "단팥", en: "sweet red bean" },
      { ko: "소박하다", en: "to be simple, humble" },
    ],
    quiz: [
      { q: { ko: "두 친구가 산책할 때 길가에 물든 나무는 무엇이에요?", en: "What tree was colored along the street when they took a walk?" },
        options: ["소나무", "은행나무", "벚나무", "사과나무"], answer: 1 },
      { q: { ko: "산책 후 편의점에서 사 먹은 간식은 무엇이에요?", en: "What snack did they buy and eat at the convenience store after the walk?" },
        options: ["아이스크림", "어묵", "호빵", "군밤"], answer: 2 },
    ],
  },
  {
    id: 'sb-28', lv: 3,
    title: { ko: "어느 날의 정전 소동", en: "The Blackout Commotion of One Day" },
    blurb: { ko: "갑자기 불이 꺼진 저녁, 양초를 켜고 도란도란 이야기를 나눠요.", en: "On an evening when the power suddenly went out, lighting candles and chatting warmly." },
    pages: [
      { who: 'n',       ko: "비바람이 세차게 치던 여름밤, 감자와 치즈가 거실에서 텔레비전을 보고 있었습니다.", en: "On a summer night with stormy rain, Potato and Cheese were watching television in the living room." },
      { who: 'n',       ko: "갑자기 펑 하는 소리와 함께 방 안의 모든 전등과 전자기기가 일제히 꺼졌습니다.", en: "Suddenly with a pop sound, all lights and electronic devices in the room went out at once." },
      { who: 'cheese',  ko: "\"앗, 온 세상이 캄캄해졌어요! 번개 때문에 동네 전기가 나간 것 같아요.\"", en: "\"Ah, the whole world became pitch-dark! It seems electricity went out due to lightning.\"" },
      { who: 'potato',  ko: "\"스마트폰 손전등을 켤 테니까 거기 가만히 계세요. 서랍에 촛불이 있어요.\"", en: "\"I will turn on the smartphone flashlight so please stay still. There are candles in the drawer.\"" },
      { who: 'n',       ko: "감자는 조심조심 서랍을 뒤져 하얀 양초 두 자루와 성냥을 찾아왔습니다.", en: "Potato carefully searched the drawer and brought two white candles and matches." },
      { who: 'n',       ko: "식탁 위에 촛불을 켜자 은은하고 부드러운 노란 불빛이 어두운 방을 따뜻하게 밝혔습니다.", en: "When lighting candles on the table, soft yellow candlelight warmly illuminated the dark room." },
      { who: 'cheese',  ko: "\"전기가 끊기니까 냉장고 소리도 안 나고 빗소리만 조용히 들리네요.\"", en: "\"With power cut, there is no refrigerator noise and only rain sounds can be heard quietly.\"" },
      { who: 'potato',  ko: "\"텔레비전도 스마트폰도 볼 수 없지만, 오히려 마음이 아주 차분해지는 것 같아요.\"", en: "\"We cannot watch TV or smartphones, but rather the heart feels so peaceful.\"" },
      { who: 'n',       ko: "두 친구는 촛불 주위에 둘러앉아 어린 시절의 추억과 재미있는 옛날이야기를 나누었습니다.", en: "The two friends sat around the candlelight and shared childhood memories and interesting past stories." },
      { who: 'cheese',  ko: "\"불편할 줄 알았던 정전이 뜻밖의 다정한 대화 시간을 선물해 주었네요.\"", en: "\"The blackout we thought would be inconvenient gifted us an unexpectedly sweet conversation time.\"" },
      { who: 'n',       ko: "한 시간쯤 지나자 환하게 전등이 다시 켜졌지만, 두 친구는 촛불을 바로 끄지 않았습니다.", en: "About an hour later the lights brightly turned back on, but the two friends did not blow out the candles right away." },
      { who: 'potato',  ko: "\"가끔은 이렇게 모든 기계를 끄고 조용히 대화를 나누는 밤도 참 소중한 것 같아요.\"", en: "\"Sometimes nights like this, turning off all devices and chatting quietly, are truly precious.\"" },
    ],
    words: [
      { ko: "정전", en: "blackout, power outage" },
      { ko: "캄캄하다", en: "to be pitch-dark" },
      { ko: "손전등", en: "flashlight" },
      { ko: "양초", en: "candle" },
      { ko: "성냥", en: "matches" },
      { ko: "추억", en: "memory, recollection" },
    ],
    quiz: [
      { q: { ko: "갑자기 방 안이 어두워진 까닭은 무엇이에요?", en: "Why did the room suddenly become dark?" },
        options: ["전등이 고장 나서", "번개로 정전이 되어서", "창문을 닫아서", "밤이 깊어서"], answer: 1 },
      { q: { ko: "어둠 속에서 방을 밝히기 위해 켠 것은 무엇이에요?", en: "What did they light to brighten the room in the dark?" },
        options: ["손전등만", "텔레비전 화면", "양초 촛불", "모닥불"], answer: 2 },
    ],
  },
  {
    id: 'sb-29', lv: 3,
    title: { ko: "옥상 텃밭의 첫 수확", en: "First Harvest on the Rooftop Garden" },
    blurb: { ko: "봄부터 정성껏 가꾼 옥상 화분에서 방울토마토와 상추를 따요.", en: "Picking cherry tomatoes and lettuce from rooftop pots tended devotedly since spring." },
    pages: [
      { who: 'n',       ko: "따스한 초여름 아침, 감자와 치즈는 물뿌리개를 들고 빌라 옥상 텃밭으로 올라갔습니다.", en: "On a warm early summer morning, Potato and Cheese carried watering cans and went up to the rooftop garden." },
      { who: 'potato',  ko: "\"치즈 씨, 저기 보세요! 우리가 지난봄에 심었던 방울토마토가 빨갛게 익었어요.\"", en: "\"Cheese, look over there! The cherry tomatoes we planted last spring have ripened red.\"" },
      { who: 'cheese',  ko: "\"어머나, 정말 앵두처럼 붉고 탐스럽네요! 상추 잎도 아주 무성하게 자랐어요.\"", en: "\"Oh my, they are really red and appetizing like cherries! The lettuce leaves have grown lushly too.\"" },
      { who: 'n',       ko: "두 친구는 작은 바구니를 내려놓고 조심스럽게 방울토마토를 하나씩 땄습니다.", en: "The two friends set down small baskets and carefully picked cherry tomatoes one by one." },
      { who: 'cheese',  ko: "\"상추는 겉잎부터 한 장씩 똑똑 뜯어야 안쪽 잎이 계속 자랄 수 있대요.\"", en: "\"They say we must snap off outer leaves one by one so that inner leaves can continue growing.\"" },
      { who: 'potato',  ko: "\"매일 아침 옥상에 올라와 잡초를 뽑고 물을 준 보람이 있네요.\"", en: "\"Coming up to the roof every morning, weeding and watering, was truly rewarding.\"" },
      { who: 'n',       ko: "바구니 가득 싱그러운 채소와 새빨간 토마토가 소복하게 담겼습니다.", en: "The basket was piled high with refreshing vegetables and bright red tomatoes." },
      { who: 'cheese',  ko: "\"옥상에서 갓 딴 채소라 마트에서 파는 것보다 훨씬 신선하고 향이 진해요.\"", en: "\"Being freshly picked from the roof, they are much fresher and have deeper scents than mart ones.\"" },
      { who: 'potato',  ko: "\"오늘 점심에는 우리가 직접 수확한 채소로 비빔밥을 만들어 먹어요.\"", en: "\"For lunch today, let's make and eat bibimbap with vegetables we harvested ourselves.\"" },
      { who: 'n',       ko: "두 친구는 기쁜 마음으로 옥상 수돗가에서 딴 채소를 깨끗한 물로 씻었습니다.", en: "The two friends washed the picked vegetables with clean water at the rooftop faucet with joyous hearts." },
      { who: 'cheese',  ko: "\"작은 씨앗이 이렇게 자라 열매를 맺는 걸 보니 자연은 참 신비로워요.\"", en: "\"Seeing small seeds grow like this and bear fruit, nature is truly miraculous.\"" },
      { who: 'potato',  ko: "\"우리 가을에는 무와 배추도 심어 봐요. 농사짓는 재미에 푹 빠졌어요.\"", en: "\"Let's plant radishes and cabbages in autumn too. I fell completely in love with farming fun.\"" },
    ],
    words: [
      { ko: "텃밭", en: "vegetable garden" },
      { ko: "방울토마토", en: "cherry tomato" },
      { ko: "상추", en: "lettuce" },
      { ko: "수확", en: "harvest" },
      { ko: "잡초", en: "weed" },
      { ko: "신비롭다", en: "to be mysterious, miraculous" },
    ],
    quiz: [
      { q: { ko: "두 친구가 옥상 텃밭에서 수확한 것은 무엇이에요?", en: "What did the two friends harvest at the rooftop garden?" },
        options: ["오이와 가지", "방울토마토와 상추", "호박과 감자", "딸기와 사과"], answer: 1 },
      { q: { ko: "수확한 채소로 점심에 무엇을 만들어 먹기로 했어요?", en: "What did they decide to make and eat for lunch with the harvested vegetables?" },
        options: ["된장국", "비빔밥", "볶음밥", "샐러드 빵"], answer: 1 },
    ],
  },
  {
    id: 'sb-30', lv: 3,
    title: { ko: "비둘기와 작은 벤치", en: "Pigeons and the Little Bench" },
    blurb: { ko: "동네 작은 분수대 앞 벤치에서 평화로운 오후를 보내요.", en: "Spending a peaceful afternoon on the bench in front of the neighborhood fountain." },
    pages: [
      { who: 'n',       ko: "바람이 살랑거리는 맑은 수요일 오후, 감자와 치즈는 동네 작은 광장으로 산책을 나왔습니다.", en: "On a clear Wednesday afternoon with gentle breeze, Potato and Cheese came out to walk in the small neighborhood plaza." },
      { who: 'n',       ko: "광장 중앙 분수대에서는 시원한 물줄기가 솟아오르고 비둘기들이 모여 있었습니다.", en: "At the plaza center fountain, cool jets of water rose and pigeons gathered." },
      { who: 'cheese',  ko: "\"날씨가 너무 좋아서 집에만 있기 아까웠는데, 나오길 정말 잘했어요.\"", en: "\"Because the weather is so nice it felt like a waste to stay home, coming out was so right.\"" },
      { who: 'potato',  ko: "\"저기 등나무 꽃 그늘 밑에 빈 벤치가 있어요. 저기 앉아서 쉬어요.\"", en: "\"Over there under the wisteria flower shade is an empty bench. Let's sit there and rest.\"" },
      { who: 'n',       ko: "두 친구는 벤치에 나란히 앉아 가방에서 보온병에 담아 온 따뜻한 둥굴레차를 꺼냈습니다.", en: "The two friends sat side by side on the bench and took out warm Solomon's seal tea brought in a thermos." },
      { who: 'cheese',  ko: "\"차 향기가 참 구수해요. 분수대 물소리를 들으니 복잡한 생각이 사라져요.\"", en: "\"The tea scent is so savory. Listening to fountain water sounds makes complicated thoughts vanish.\"" },
      { who: 'n',       ko: "그때 비둘기 몇 마리가 총총 걸음으로 벤치 근처로 다가와 고개를 갸웃거렸습니다.", en: "Just then, several pigeons hopped closer to the bench and tilted their heads." },
      { who: 'potato',  ko: "\"비둘기들도 산책을 나온 모양이에요. 사람을 무서워하지 않고 참 평화로워요.\"", en: "\"It looks like the pigeons came out for a walk too. They aren't scared of humans and are so peaceful.\"" },
      { who: 'cheese',  ko: "\"도시 한가운데에 이렇게 자연을 느끼며 쉴 수 있는 쉼터가 있다는 게 참 감사해요.\"", en: "\"Having a shelter where one can rest feeling nature in the middle of a city is truly thankful.\"" },
      { who: 'n',       ko: "광장 시계탑이 네 시를 알리는 맑은 종소리를 은은하게 울렸습니다.", en: "The plaza clock tower faintly rang a clear chime announcing four o'clock." },
      { who: 'potato',  ko: "\"시간이 천천히 흘러가는 것 같아요. 가끔은 이런 느린 휴식이 꼭 필요해요.\"", en: "\"It feels like time flows slowly. Sometimes such slow rest is definitely needed.\"" },
      { who: 'cheese',  ko: "\"맞아요. 바쁜 일상 속에서 이렇게 마음에 쉼표를 찍는 날이 참 소중해요.\"", en: "\"Right. Days putting a comma in the heart like this amidst busy daily routines are so precious.\"" },
    ],
    words: [
      { ko: "분수대", en: "fountain" },
      { ko: "등나무", en: "wisteria" },
      { ko: "둥굴레차", en: "Solomon's seal tea" },
      { ko: "총총", en: "hoppingly, with quick small steps" },
      { ko: "쉼터", en: "resting place, shelter" },
      { ko: "휴식", en: "rest, break" },
    ],
    quiz: [
      { q: { ko: "두 친구가 벤치에서 마신 차는 무엇이에요?", en: "What tea did the two friends drink on the bench?" },
        options: ["녹차", "둥굴레차", "홍차", "유자차"], answer: 1 },
      { q: { ko: "두 사람이 앉아서 쉰 벤치는 어디 밑에 있었어요?", en: "Under what was the bench where the two sat and rested?" },
        options: ["은행나무 밑", "등나무 꽃 그늘 밑", "시계탑 바로 밑", "지하철 입구 옆"], answer: 1 },
    ],
  },
];
