/* ══════════════════════════════════════════════════════════════
   여행 한국어 (Travel Korean) 데이터베이스
   ──────────────────────────────────────────────────────────────
   외국인 여행객이 한국에서 가장 많이 마주치는 7개 핵심 상황과
   43개 실전 구문 목록.
   난이도별 3단계(쉬운 버전 / 보통 버전 / 정확한 버전) 완벽 지원.
   ══════════════════════════════════════════════════════════════ */

export const TRAVEL_CATEGORIES = [
  { id: 'air',   emoji: '✈️', ko: '공항 & 입국',       en: 'Airport & Arrival',       desc: '입국 심사, 환전, 유심, 짐 찾기' },
  { id: 'trans', emoji: '🚇', ko: '교통 & 길 찾기',     en: 'Transit & Directions',     desc: '지하철, 버스, 택시, 길 묻기' },
  { id: 'hotel', emoji: '🏨', ko: '숙소 & 호텔',       en: 'Hotel & Stay',            desc: '체크인, 짐 보관, 룸 요청' },
  { id: 'dine',  emoji: '🍽️', ko: '식당 & 카페',       en: 'Dining & Cafe',           desc: '주문, 반찬/물 요청, 맵기 조절, 계산' },
  { id: 'shop',  emoji: '🛍️', ko: '쇼핑 & 편의점',     en: 'Shopping & Store',        desc: '가격 묻기, 사이즈, 편의점, 택스프리' },
  { id: 'tour',  emoji: '📸', ko: '관광 & K-컬처',     en: 'Sightseeing & Culture',   desc: '티켓 구매, 사진 부탁, 한복 체험' },
  { id: 'help',  emoji: '🚨', ko: '약국 & 긴급상황',   en: 'Pharmacy & Emergency',    desc: '약국 증상 설명, 분실물, 도움 요청' },
];

/* 각 상황별 꼭 알아야 하는 필수 어휘 (Vocabulary) */
export const TRAVEL_VOCAB = {
  air: [
    { ko: '여권', en: 'Passport', pron: 'yeogwon' },
    { ko: '짐 / 수하물', en: 'Luggage / Baggage', pron: 'jim / suhamul' },
    { ko: '유심 카드', en: 'SIM card', pron: 'yusim kadeu' },
    { ko: '환전소', en: 'Currency exchange', pron: 'hwanjeonso' },
    { ko: '공항철도', en: 'Airport railroad (AREX)', pron: 'gonghang-cheoldo' },
    { ko: '입국 심사', en: 'Immigration / Entry review', pron: 'ipguk simsa' },
  ],
  trans: [
    { ko: '교통카드 (티머니)', en: 'Transit card (T-money)', pron: 'gyotong kadeu' },
    { ko: '충전', en: 'Top-up / Recharge', pron: 'chungjeon' },
    { ko: '지하철역', en: 'Subway station', pron: 'jihacheol-yeok' },
    { ko: '출구', en: 'Exit', pron: 'chulgu' },
    { ko: '화장실', en: 'Restroom / Toilet', pron: 'hwajangsil' },
    { ko: '택시', en: 'Taxi', pron: 'taeksi' },
  ],
  hotel: [
    { ko: '체크인 / 체크아웃', en: 'Check-in / Check-out', pron: 'chekeu-in / chekeu-aut' },
    { ko: '짐 보관', en: 'Luggage storage', pron: 'jim bogwan' },
    { ko: '와이파이', en: 'Wi-Fi', pron: 'waipai' },
    { ko: '수건', en: 'Towel', pron: 'sugeon' },
    { ko: '방 (객실)', en: 'Room', pron: 'bang' },
    { ko: '에어컨 / 난방', en: 'Air conditioner / Heating', pron: 'eeokeon / nanbang' },
  ],
  dine: [
    { ko: '메뉴판', en: 'Menu', pron: 'menyupan' },
    { ko: '물', en: 'Water', pron: 'mul' },
    { ko: '반찬', en: 'Side dishes', pron: 'banchan' },
    { ko: '앞치마', en: 'Apron', pron: 'apchima' },
    { ko: '맵다 (덜 맵게)', en: 'Spicy (Less spicy)', pron: 'maepda (deol maepge)' },
    { ko: '포장 (테이크아웃)', en: 'To-go / Takeout', pron: 'pojang' },
    { ko: '계산 / 영수증', en: 'Bill / Receipt', pron: 'gyesan / yeongsujeung' },
  ],
  shop: [
    { ko: '얼마', en: 'How much', pron: 'eolma' },
    { ko: '입어보다', en: 'Try on', pron: 'ibeoboda' },
    { ko: '사이즈 / 색상', en: 'Size / Color', pron: 'saijeu / saeksang' },
    { ko: '봉투', en: 'Plastic bag', pron: 'bongtu' },
    { ko: '할인 / 행사 (1+1)', en: 'Discount / Buy 1 Get 1', pron: 'harin / haengsa' },
    { ko: '면세 (택스프리)', en: 'Tax free / Refund', pron: 'myeonse (taekseupeuri)' },
  ],
  tour: [
    { ko: '입장권 / 표', en: 'Ticket', pron: 'ipjang-gwon / pyo' },
    { ko: '성인 / 어린이', en: 'Adult / Child', pron: 'seong-in / eorini' },
    { ko: '사진', en: 'Photo', pron: 'sajin' },
    { ko: '한복', en: 'Hanbok (Traditional dress)', pron: 'hanbok' },
    { ko: '추천', en: 'Recommendation', pron: 'chucheon' },
    { ko: '지도', en: 'Map', pron: 'jido' },
  ],
  help: [
    { ko: '약국', en: 'Pharmacy', pron: 'yakguk' },
    { ko: '두통약 / 소화제', en: 'Headache / Digestive medicine', pron: 'dutongyak / sohwaje' },
    { ko: '밴드 / 소독약', en: 'Bandage / Antiseptic', pron: 'baendeu / sodokyak' },
    { ko: '지갑 / 핸드폰', en: 'Wallet / Phone', pron: 'jigap / haendeupon' },
    { ko: '경찰서', en: 'Police station', pron: 'gyeongchalseo' },
    { ko: '도와주세요', en: 'Please help me', pron: 'dowajuseyo' },
  ],
};

export const TRAVEL_PHRASES = [
  // ── 1. 공항 & 입국 (Airport & Arrival) ──────────────────────
  {
    id: 'tv-air-01', cat: 'air',
    title: '여권 제시하기',
    easy: { ko: '여권이요.', pron: 'Yeogwon-iyo.', en: 'Passport, please.' },
    std:  { ko: '여권 여기 있습니다.', pron: 'Yeogwon yeogi itseumnida.', en: 'Here is my passport.' },
    pro:  { ko: '제 여권 여기 있습니다.', pron: 'Je yeogwon yeogi itseumnida.', en: 'Here is my passport, sir/ma’am.' },
    tip: '입국 심사대나 면세점에서 여권을 건넬 때 씁니다.',
  },
  {
    id: 'tv-air-02', cat: 'air',
    title: '입국 목적 말하기',
    easy: { ko: '여행이요.', pron: 'Yeohaeng-iyo.', en: 'Travel.' },
    std:  { ko: '여행하러 왔어요.', pron: 'Yeohaenghareo wasseoyo.', en: 'I am here for traveling.' },
    pro:  { ko: '관광 목적으로 방문했습니다.', pron: 'Gwangwang mokjeok-euro bangmunhaesseumnida.', en: 'I visited for sightseeing purposes.' },
    tip: '입국 목적을 물어볼 때 간단히 답하는 표현입니다.',
  },
  {
    id: 'tv-air-03', cat: 'air',
    title: '수하물 수취대 찾기',
    easy: { ko: '짐 어디예요?', pron: 'Jim eodiyeyo?', en: 'Where is luggage?' },
    std:  { ko: '짐은 어디서 찾아요?', pron: 'Jimeun eodiseo chajayo?', en: 'Where can I pick up my luggage?' },
    pro:  { ko: '수하물 찾는 곳이 어디에 있나요?', pron: 'Suhamul chatneun gosi eodie innayo?', en: 'Could you tell me where the baggage claim is?' },
    tip: '수하물 수취대(Baggage Claim)를 찾을 때 묻습니다.',
  },
  {
    id: 'tv-air-04', cat: 'air',
    title: '유심 카드 구매처 문의',
    easy: { ko: '유심 어디 있어요?', pron: 'Yusim eodi isseoyo?', en: 'Where is SIM card?' },
    std:  { ko: '유심 카드 어디서 살 수 있어요?', pron: 'Yusim kadeu eodiseo sal su isseoyo?', en: 'Where can I buy a SIM card?' },
    pro:  { ko: '여행자용 유심 카드는 어디서 구매할 수 있나요?', pron: 'Yeohaengjayong yusim kadeu-neun eodiseo gumaehal su innayo?', en: 'Where can I purchase a traveler SIM card?' },
    tip: '공항 입국장에서 선불 유심이나 eSIM 안내 데스크를 찾을 때 씁니다.',
  },
  {
    id: 'tv-air-05', cat: 'air',
    title: '환전소 찾기',
    easy: { ko: '환전소 어디예요?', pron: 'Hwanjeonso eodiyeyo?', en: 'Where is exchange?' },
    std:  { ko: '환전소는 어디에 있어요?', pron: 'Hwanjeonso-neun eodie isseoyo?', en: 'Where is the currency exchange?' },
    pro:  { ko: '가장 가까운 환전소가 어디에 있나요?', pron: 'Gajang gakkaun hwanjeonso-ga eodie innayo?', en: 'Where is the nearest currency exchange booth?' },
    tip: '원화로 환전하거나 현금을 인출할 때 유용합니다.',
  },
  {
    id: 'tv-air-06', cat: 'air',
    title: '공항철도 탑승구 찾기',
    easy: { ko: '공항철도 어디예요?', pron: 'Gonghang-cheoldo eodiyeyo?', en: 'Where is the airport train?' },
    std:  { ko: '서울역 가는 공항철도는 어디서 타요?', pron: 'Seoul-yeok ganeun gonghang-cheoldo-neun eodiseo tayo?', en: 'Where do I take the airport train to Seoul Station?' },
    pro:  { ko: '서울역 방면 공항철도 타는 곳은 어디로 가야 하나요?', pron: 'Seoul-yeok bangmyeon gonghang-cheoldo taneun goseun eodiro gaya hanayo?', en: 'Which way should I go to take the airport train to Seoul Station?' },
    tip: '인천공항에서 AREX 열차를 타러 갈 때 씁니다.',
  },

  // ── 2. 교통 & 길 찾기 (Transit & Directions) ────────────────
  {
    id: 'tv-trans-01', cat: 'trans',
    title: '교통카드 충전 요청',
    easy: { ko: '티머니 충전이요.', pron: 'T-meoni chungjeon-iyo.', en: 'T-money top-up, please.' },
    std:  { ko: '티머니 카드 충전해 주세요.', pron: 'T-meoni kadeu chungjeonhae juseyo.', en: 'Please top up my T-money card.' },
    pro:  { ko: '이 교통카드에 만 원만 충전 부탁드립니다.', pron: 'I gyotongkadeu-e man wonman chungjeon butakdeurimnida.', en: 'Could you please top up 10,000 won on this transit card?' },
    tip: '편의점이나 지하철 역무실에서 교통카드를 충전할 때 씁니다.',
  },
  {
    id: 'tv-trans-02', cat: 'trans',
    title: '택시 목적지 말하기',
    easy: { ko: '홍대입구역 가주세요.', pron: 'Hongdaeipgu-yeok gajuseyo.', en: 'Hongdae station, please.' },
    std:  { ko: '홍대입구역으로 가주세요.', pron: 'Hongdaeipgu-yeog-euro gajuseyo.', en: 'Please take me to Hongik University Station.' },
    pro:  { ko: '기사님, 홍대입구역 2번 출구 쪽으로 가주실 수 있나요?', pron: 'Gisanim, Hongdaeipgu-yeok ibeon chulgu jjog-euro gajusil su innayo?', en: 'Driver, could you please take me towards Exit 2 of Hongdae Station?' },
    tip: '택시를 탔을 때 목적지를 말하는 만능 표현입니다.',
  },
  {
    id: 'tv-trans-03', cat: 'trans',
    title: '택시 트렁크 요청',
    easy: { ko: '트렁크 열어주세요.', pron: 'Teureongkeu yeoreojuseyo.', en: 'Open trunk, please.' },
    std:  { ko: '트렁크 좀 열어주실 수 있나요?', pron: 'Teureongkeu jom yeoreojusil su innayo?', en: 'Could you please open the trunk?' },
    pro:  { ko: '기사님, 짐이 있어서 그러는데 트렁크 좀 부탁드릴게요.', pron: 'Gisanim, jimi isseoseo geureoneunde teureongkeu jom butakdeurilgeyo.', en: 'Driver, I have luggage, could you please pop the trunk?' },
    tip: '택시에 큰 캐리어를 실어야 할 때 기사님께 부탁합니다.',
  },
  {
    id: 'tv-trans-04', cat: 'trans',
    title: '하차 요청',
    easy: { ko: '여기서 내려주세요.', pron: 'Yeogiseo naeryeojuseyo.', en: 'Drop me off here.' },
    std:  { ko: '여기서 내려주시면 돼요.', pron: 'Yeogiseo naeryeojusimyeon dwaeyo.', en: 'Please let me off right here.' },
    pro:  { ko: '저기 신호등 앞쪽에서 내려주시면 감사하겠습니다.', pron: 'Jeogi sinhodeung apjjog-eseo naeryeojusimyeon gamsahagesseumnida.', en: 'I would appreciate it if you could drop me off in front of the traffic light.' },
    tip: '택시에서 내리고 싶은 지점에 도착했을 때 씁니다.',
  },
  {
    id: 'tv-trans-05', cat: 'trans',
    title: '화장실 위치 묻기',
    easy: { ko: '화장실 어디예요?', pron: 'Hwajangsil eodiyeyo?', en: 'Where is restroom?' },
    std:  { ko: '화장실이 어디에 있어요?', pron: 'Hwajangsil-i eodie isseoyo?', en: 'Where is the restroom located?' },
    pro:  { ko: '실례지만, 가까운 화장실이 어디에 있나요?', pron: 'Sillyejiman, gakkaun hwajangsil-i eodie innayo?', en: 'Excuse me, could you tell me where the nearest restroom is?' },
    tip: '여행 중 가장 많이 쓰게 되는 필수 생존 질문입니다.',
  },
  {
    id: 'tv-trans-06', cat: 'trans',
    title: '도보 이동 가능 여부',
    easy: { ko: '걸어서 갈 수 있어요?', pron: 'Georeoseo gal su isseoyo?', en: 'Can I walk there?' },
    std:  { ko: '여기서 걸어서 갈 수 있어요?', pron: 'Yeogiseo georeoseo gal su isseoyo?', en: 'Can I walk there from here?' },
    pro:  { ko: '여기서 도보로 이동 가능한 거리인가요?', pron: 'Yeogiseo doboro idong ganeunghan geori-ingayo?', en: 'Is it within walking distance from here?' },
    tip: '목적지가 도보 거리인지 확인할 때 씁니다.',
  },

  // ── 3. 숙소 & 호텔 (Hotel & Accommodation) ──────────────────
  {
    id: 'tv-hotel-01', cat: 'hotel',
    title: '체크인 요청',
    easy: { ko: '체크인이요.', pron: 'Chekeu-in-iyo.', en: 'Check-in, please.' },
    std:  { ko: '체크인하고 싶어요.', pron: 'Chekeu-in-hago sipeoyo.', en: 'I’d like to check in.' },
    pro:  { ko: '예약자 홍길동인데요, 체크인 부탁드립니다.', pron: 'Yeyakja Hong Gil-dong-inde-yo, chekeu-in butakdeurimnida.', en: 'I have a reservation under Hong Gil-dong, check-in please.' },
    tip: '호텔이나 숙소 프론트 데스크에 도착했을 때 첫인사로 씁니다.',
  },
  {
    id: 'tv-hotel-02', cat: 'hotel',
    title: '체크인 전 짐 보관',
    easy: { ko: '짐 맡길게요.', pron: 'Jim matgilgeyo.', en: 'Leave luggage here.' },
    std:  { ko: '체크인 전에 짐 좀 맡길 수 있나요?', pron: 'Chekeu-in jeone jim jom matgil su innayo?', en: 'Can I leave my luggage before check-in?' },
    pro:  { ko: '체크인 시간 전인데, 짐을 먼저 보관해 주실 수 있을까요?', pron: 'Chekeu-in sigan jeoninde, jimeul meonjeo bogwanhae jusil su isseulkkayo?', en: 'It is before check-in time, but could you please store my luggage first?' },
    tip: '체크인 시간 전에 도착해 먼저 짐을 보관하고 싶을 때 씁니다.',
  },
  {
    id: 'tv-hotel-03', cat: 'hotel',
    title: '와이파이 비밀번호 문의',
    easy: { ko: '와이파이 뭐예요?', pron: 'Waipai mwoyeyo?', en: 'What is Wi-Fi?' },
    std:  { ko: '와이파이 비밀번호가 뭐예요?', pron: 'Waipai bimilbeonhoga mwoyeyo?', en: 'What is the Wi-Fi password?' },
    pro:  { ko: '객실 와이파이 비밀번호 좀 알려주시겠어요?', pron: 'Gaeksil waipai bimilbeonho jom allyeojusigesseoyo?', en: 'Could you please let me know the room Wi-Fi password?' },
    tip: '호텔이나 카페에서 인터넷 연결 정보를 물어볼 때 씁니다.',
  },
  {
    id: 'tv-hotel-04', cat: 'hotel',
    title: '수건 추가 요청',
    easy: { ko: '수건 더 주세요.', pron: 'Sugeon deo juseyo.', en: 'More towels, please.' },
    std:  { ko: '수건 더 주실 수 있나요?', pron: 'Sugeon deo jusil su innayo?', en: 'Could I have more towels?' },
    pro:  { ko: '죄송하지만 수건 두 장만 더 챙겨주실 수 있을까요?', pron: 'Joesonghajiman sugeon du jangman deo chaenggyeojusil su isseulkkayo?', en: 'Excuse me, could you please provide two more towels for our room?' },
    tip: '객실에 수건이 부족할 때 프론트에 요청하는 말입니다.',
  },
  {
    id: 'tv-hotel-05', cat: 'hotel',
    title: '방 온도 상태 알리기',
    easy: { ko: '방이 추워요 / 더워요.', pron: 'Bangi chuwoyo / deowoyo.', en: 'Room is cold / hot.' },
    std:  { ko: '방이 좀 추운데 / 더운데 어떻게 해요?', pron: 'Bangi jom chuwunde / deowunde eotteoke haeyo?', en: 'The room is a bit cold / hot, what should I do?' },
    pro:  { ko: '방 온도가 너무 낮아서(높아서) 난방(에어컨) 조절 부탁드립니다.', pron: 'Bang ondoga neomu najaseo nanbang jojeol butakdeurimnida.', en: 'The room temperature is uncomfortable, could you please adjust the heating/AC?' },
    tip: '온도 조절이나 에어컨/난방 문의 시 씁니다.',
  },
  {
    id: 'tv-hotel-06', cat: 'hotel',
    title: '체크아웃 하기',
    easy: { ko: '체크아웃이요.', pron: 'Chekeu-aut-iyo.', en: 'Check-out.' },
    std:  { ko: '체크아웃할게요.', pron: 'Chekeu-aut-halgeyo.', en: 'I’d like to check out.' },
    pro:  { ko: '302호 체크아웃하겠습니다. 잘 묵고 갑니다.', pron: 'Sambaegi-ho chekeu-aut-hagesseumnida. Jal mukgo gamnida.', en: 'Checking out of room 302. Thank you for the wonderful stay.' },
    tip: '숙소를 떠날 때 키를 반납하며 건네는 말입니다.',
  },

  // ── 4. 식당 & 카페 (Dining & Cafe) ──────────────────────────
  {
    id: 'tv-dine-01', cat: 'dine',
    title: '인원수 알리고 자리 잡기',
    easy: { ko: '두 명이요.', pron: 'Du myeong-iyo.', en: 'Two people.' },
    std:  { ko: '두 명이에요. 자리 있어요?', pron: 'Du myeong-ieyo. Jari isseoyo?', en: 'Table for two, please. Do you have seats?' },
    pro:  { ko: '안녕하세요, 두 명인데 지금 식사 가능한가요?', pron: 'Annyeonghaseyo, du myeong-inde jigeum siksa ganeunghangayo?', en: 'Hello, party of two, is it possible to dine now?' },
    tip: '식당에 들어서며 인원수를 알릴 때 씁니다.',
  },
  {
    id: 'tv-dine-02', cat: 'dine',
    title: '메뉴판 요청',
    easy: { ko: '메뉴판이요.', pron: 'Menyupan-iyo.', en: 'Menu.' },
    std:  { ko: '메뉴판 주세요.', pron: 'Menyupan juseyo.', en: 'Menu, please.' },
    pro:  { ko: '저기요, 메뉴판 좀 가져다주시겠어요?', pron: 'Jeogiyo, menyupan jom gajyeodajusigesseoyo?', en: 'Excuse me, could you please bring us the menu?' },
    tip: '메뉴판을 보고 싶을 때 직원에게 요청합니다.',
  },
  {
    id: 'tv-dine-03', cat: 'dine',
    title: '손가락 가리키며 주문',
    easy: { ko: '이거요 / 이거 주세요.', pron: 'Igeo-yo / Igeo juseyo.', en: 'This / This, please.' },
    std:  { ko: '이거 하나 주세요.', pron: 'Igeo hana juseyo.', en: 'One of this, please.' },
    pro:  { ko: '여기 이 메뉴로 1인분 부탁드릴게요.', pron: 'Yeogi i menyu-ro irinbun butakdeurilgeyo.', en: 'Could we please order one serving of this menu item?' },
    tip: '메뉴를 손가락으로 가리키며 주문할 때 가장 유용한 만능 표현입니다.',
  },
  {
    id: 'tv-dine-04', cat: 'dine',
    title: '맵기 조절 부탁',
    easy: { ko: '안 맵게요.', pron: 'An maepgeyo.', en: 'Not spicy, please.' },
    std:  { ko: '덜 맵게 해주세요.', pron: 'Deol maepge haejuseyo.', en: 'Please make it less spicy.' },
    pro:  { ko: '제가 매운 음식을 잘 못 먹어서, 최대한 덜 맵게 부탁드립니다.', pron: 'Jega maeun eumsig-eul jal mot meogeoseo, choedaehan deol maepge butakdeurimnida.', en: 'I cannot handle spicy food well, could you please make it as mild as possible?' },
    tip: '한국 음식이 매울까 봐 걱정될 때 꼭 써야 하는 필수 표현입니다.',
  },
  {
    id: 'tv-dine-05', cat: 'dine',
    title: '물 리필 요청',
    easy: { ko: '물이요 / 물 주세요.', pron: 'Mul-iyo / Mul juseyo.', en: 'Water, please.' },
    std:  { ko: '물 좀 더 주세요.', pron: 'Mul jom deo juseyo.', en: 'More water, please.' },
    pro:  { ko: '여기 시원한 물 한 통만 더 부탁드릴게요.', pron: 'Yeogi siwonhan mul han tongman deo butakdeurilgeyo.', en: 'Excuse me, could we please have another bottle of cold water?' },
    tip: '식사 중 물이나 기본 반찬을 더 요청할 때 씁니다.',
  },
  {
    id: 'tv-dine-06', cat: 'dine',
    title: '앞치마 찾기',
    easy: { ko: '앞치마요.', pron: 'Apchima-yo.', en: 'Apron.' },
    std:  { ko: '앞치마 있어요?', pron: 'Apchima isseoyo?', en: 'Do you have an apron?' },
    pro:  { ko: '죄송한데 앞치마 어디에 있는지 알 수 있을까요?', pron: 'Joesonghande apchima eodie inneunji al su isseulkkayo?', en: 'Excuse me, could you tell me where I can find an apron?' },
    tip: '국물 요리나 고기를 먹을 때 옷에 튀지 않게 앞치마를 찾을 때 씁니다.',
  },
  {
    id: 'tv-dine-07', cat: 'dine',
    title: '카페 포장 주문',
    easy: { ko: '아아 테이크아웃이요.', pron: 'A-a teikeu-aut-iyo.', en: 'Iced Americano to go.' },
    std:  { ko: '아이스 아메리카노 한 잔 포장해 주세요.', pron: 'Aiseu Amerikano han jan pojanghae juseyo.', en: 'One iced Americano to go, please.' },
    pro:  { ko: '아이스 아메리카노 테이크아웃으로 한 잔 부탁드립니다.', pron: 'Aiseu Amerikano teikeu-aut-euro han jan butakdeurimnida.', en: 'Could I please get one iced Americano for takeout?' },
    tip: '카페에서 테이크아웃 주문할 때 쓰는 정석 표현입니다.',
  },
  {
    id: 'tv-dine-08', cat: 'dine',
    title: '계산하기 & 영수증',
    easy: { ko: '계산이요.', pron: 'Gyesan-iyo.', en: 'Check, please.' },
    std:  { ko: '계산할게요. 영수증은 버려주세요.', pron: 'Gyesanhalgeyo. Yeongsujeung-eun beoryeojuseyo.', en: 'Check, please. You can throw away the receipt.' },
    pro:  { ko: '식사 다 했습니다, 계산 부탁드립니다. 영수증은 괜찮습니다.', pron: 'Siksa da haesseumnida, gyesan butakdeurimnida. Yeongsujeung-eun gwaenchanhseumnida.', en: 'We are finished dining, check please. No need for the receipt.' },
    tip: '식사를 마치고 결제할 때 쓰는 깔끔한 표현입니다.',
  },

  // ── 5. 쇼핑 & 편의점 (Shopping & Store) ─────────────────────
  {
    id: 'tv-shop-01', cat: 'shop',
    title: '가격 묻기',
    easy: { ko: '얼마예요?', pron: 'Eolmayeyo?', en: 'How much?' },
    std:  { ko: '이거 얼마예요?', pron: 'Igeo eolmayeyo?', en: 'How much is this?' },
    pro:  { ko: '죄송한데 이 상품 가격이 어떻게 되나요?', pron: 'Joesonghande i sangpum gagyeogi eotteoke doenayo?', en: 'Excuse me, could you let me know the price of this item?' },
    tip: '가격을 물어볼 때 쓰는 가장 대표적인 질문입니다.',
  },
  {
    id: 'tv-shop-02', cat: 'shop',
    title: '피팅룸 입어보기',
    easy: { ko: '입어봐도 돼요?', pron: 'Ibeobwado dwaeyo?', en: 'Can I try it on?' },
    std:  { ko: '이거 입어봐도 돼요?', pron: 'Igeo ibeobwado dwaeyo?', en: 'Can I try this on?' },
    pro:  { ko: '혹시 이 옷 피팅룸에서 한번 입어볼 수 있을까요?', pron: 'Hoksi i ot pitingrum-eseo hanbeon ibeobol su isseulkkayo?', en: 'Could I try this garment on in the fitting room?' },
    tip: '옷가게 피팅룸에서 옷을 입어보고 싶을 때 물어봅니다.',
  },
  {
    id: 'tv-shop-03', cat: 'shop',
    title: '다른 색상/사이즈 문의',
    easy: { ko: '다른 거 있어요?', pron: 'Dareun geo isseoyo?', en: 'Other one?' },
    std:  { ko: '다른 색상이나 사이즈 있어요?', pron: 'Dareun saeksang-ina sa-ijeu isseoyo?', en: 'Do you have this in another color or size?' },
    pro:  { ko: '이 제품으로 M 사이즈나 다른 색상 재고가 남아있나요?', pron: 'I jepum-euro M sa-ijeuna dareun saeksang jaegoga nam-ainnayo?', en: 'Do you have this item in size M or in other colors in stock?' },
    tip: '원하는 옷이나 신발의 다른 옵션을 찾을 때 씁니다.',
  },
  {
    id: 'tv-shop-04', cat: 'shop',
    title: '비닐봉투 거절',
    easy: { ko: '봉투 안 요.', pron: 'Bongtu an-yo.', en: 'No bag.' },
    std:  { ko: '봉투는 필요 없어요.', pron: 'Bongtu-neun piryo eopseoyo.', en: 'I don’t need a plastic bag.' },
    pro:  { ko: '그냥 들고 갈게요, 봉투는 안 주셔도 됩니다.', pron: 'Geunyang deulgo galgeyo, bongtu-neun an jusyeodo doemnida.', en: 'I will just carry it, no bag needed, thank you.' },
    tip: '편의점이나 마트 계산대에서 비닐봉투가 필요 없을 때 말합니다.',
  },
  {
    id: 'tv-shop-05', cat: 'shop',
    title: '편의점 전자레인지 찾기',
    easy: { ko: '전자레인지 어디예요?', pron: 'Jeonjareinji eodiyeyo?', en: 'Where is microwave?' },
    std:  { ko: '전자레인지는 어디에 있어요?', pron: 'Jeonjareinji-neun eodie isseoyo?', en: 'Where is the microwave?' },
    pro:  { ko: '이 도시락 데워 먹으려는데 전자레인지가 어디 있나요?', pron: 'I dosirak dewo meogeuryeoneunde jeonjareinjiga eodi innayo?', en: 'I would like to heat up this meal, where is the microwave?' },
    tip: '편의점 도시락이나 음식을 데울 때 위치를 묻습니다.',
  },
  {
    id: 'tv-shop-06', cat: 'shop',
    title: '면세(택스프리) 가능 여부',
    easy: { ko: '택스프리 돼요?', pron: 'Taekseupeuri dwaeyo?', en: 'Tax free?' },
    std:  { ko: '여기서 택스프리 받을 수 있어요?', pron: 'Yeogiseo taekseupeuri badeul su isseoyo?', en: 'Can I get a tax refund here?' },
    pro:  { ko: '외국인 면세(사후 환급) 적용이 가능한 매장인가요?', pron: 'Oegugin myeonse jeok-yong-i ganeunghan maejang-ingayo?', en: 'Is tax refund available for foreign travelers at this store?' },
    tip: '사후 면세(Tax Free) 혜택을 받을 수 있는지 확인할 때 씁니다.',
  },

  // ── 6. 관광 & K-컬처 (Sightseeing & K-Culture) ──────────────
  {
    id: 'tv-tour-01', cat: 'tour',
    title: '입장권 구매',
    easy: { ko: '한 장이요.', pron: 'Han jang-iyo.', en: 'One ticket.' },
    std:  { ko: '성인 한 장 주세요.', pron: 'Seong-in han jang juseyo.', en: 'One adult ticket, please.' },
    pro:  { ko: '성인 두 명 입장권 결제 부탁드립니다.', pron: 'Seong-in du myeong ipjang-gwon gyeolje butakdeurimnida.', en: 'Could we please purchase two adult admission tickets?' },
    tip: '궁궐, 미술관, 테마파크 매표소에서 입장권을 살 때 씁니다.',
  },
  {
    id: 'tv-tour-02', cat: 'tour',
    title: '사진 촬영 부탁',
    easy: { ko: '사진 찍어주세요.', pron: 'Sajin jjigeojuseyo.', en: 'Take a photo, please.' },
    std:  { ko: '사진 한 장만 찍어주실 수 있으세요?', pron: 'Sajin han jangman jjigeojusil su isseuseyo?', en: 'Could you please take a photo of me/us?' },
    pro:  { ko: '실례합니다만, 배경이랑 같이 사진 한 장 부탁드려도 될까요?', pron: 'Sillyehamnidaman, baegyeong-irang gachi sajin han jang butakdeuryeodo doelkkayo?', en: 'Excuse me, would you mind taking a photo of us with the background?' },
    tip: '지나가는 사람에게 정중하게 사진 촬영을 부탁할 때 씁니다.',
  },
  {
    id: 'tv-tour-03', cat: 'tour',
    title: '한복 대여 문의',
    easy: { ko: '한복 빌릴게요.', pron: 'Hanbok billilgeyo.', en: 'Rent Hanbok.' },
    std:  { ko: '한복 대여하고 싶어요.', pron: 'Hanbok daeyeohago sipeoyo.', en: 'I’d like to rent a Hanbok.' },
    pro:  { ko: '두 시간 대여로 한복 체험하고 싶은데 어떻게 하면 되나요?', pron: 'Du sigan daeyeo-ro hanbok cheheomhago sipeunde eotteoke hamyeon doenayo?', en: 'I’d like to rent Hanbok for two hours, how does the process work?' },
    tip: '경복궁이나 전주 한옥마을 등에서 한복을 빌릴 때 씁니다.',
  },
  {
    id: 'tv-tour-04', cat: 'tour',
    title: '사진 촬영 가능 여부',
    easy: { ko: '사진 돼요?', pron: 'Sajin dwaeyo?', en: 'Photo OK?' },
    std:  { ko: '여기서 사진 찍어도 돼요?', pron: 'Yeogiseo sajin jjigeodo dwaeyo?', en: 'Can I take photos here?' },
    pro:  { ko: '혹시 전시관 내부에서 사진 촬영이 허용되나요?', pron: 'Hoksi jeonsigwan naebu-eseo sajin chwaryeong-i heoyongdoenayo?', en: 'Excuse me, is photography permitted inside the exhibition hall?' },
    tip: '실내나 전시장에서 사진 촬영 가능 여부를 확인할 때 씁니다.',
  },
  {
    id: 'tv-tour-05', cat: 'tour',
    title: '현지 명소/맛집 추천',
    easy: { ko: '맛집 추천해 주세요.', pron: 'Matjip chucheonhae juseyo.', en: 'Recommend good food.' },
    std:  { ko: '추천해 주실 만한 곳이 있나요?', pron: 'Chucheonhae jusil manhan gosi innayo?', en: 'Is there any place you would recommend?' },
    pro:  { ko: '이 근처에 현지인들이 자주 가는 맛있는 식당 추천해 주실 수 있나요?', pron: 'I geuncheo-e hyeonji-indeul-i jaju ganeun masinneun sikdang chucheonhae jusil su innayo?', en: 'Could you recommend any good local restaurants that residents frequently visit?' },
    tip: '현지인이나 숙소 직원에게 맛집이나 명소를 추천받을 때 씁니다.',
  },

  // ── 7. 약국 & 긴급상황 (Pharmacy & Emergency) ───────────────
  {
    id: 'tv-help-01', cat: 'help',
    title: '비상약 구매 요청',
    easy: { ko: '두통약 / 소화제 주세요.', pron: 'Dutongyak / Sohwaje juseyo.', en: 'Headache / digestion medicine.' },
    std:  { ko: '두통약(소화제) 하나 주세요.', pron: 'Dutongyak hana juseyo.', en: 'Please give me headache medicine (digestive medicine).' },
    pro:  { ko: '머리가 아파서(속이 안 좋아서) 그러는데 잘 듣는 약 하나 부탁드립니다.', pron: 'Meoriga apaseo geureoneunde jal deunneun yak hana butakdeurimnida.', en: 'I have a headache (upset stomach), could you recommend an effective medicine?' },
    tip: '약국에서 가장 많이 찾는 비상약을 요청할 때 씁니다.',
  },
  {
    id: 'tv-help-02', cat: 'help',
    title: '상처 치료용품 구매',
    easy: { ko: '밴드 주세요.', pron: 'Baendeu juseyo.', en: 'Bandage, please.' },
    std:  { ko: '밴드랑 소독약 주세요.', pron: 'Baendeurang sodokyak juseyo.', en: 'Adhesive bandages and antiseptic, please.' },
    pro:  { ko: '발에 상처가 나서 그러는데 밴드와 바르는 연고 부탁드립니다.', pron: 'Bare sangcheoga naseo geureoneunde baendeu-wa bareuneun yeongo butakdeurimnida.', en: 'I got a cut on my foot, could I please have some bandages and antiseptic ointment?' },
    tip: '가벼운 상처가 났을 때 약국에서 치료 약품을 살 때 씁니다.',
  },
  {
    id: 'tv-help-03', cat: 'help',
    title: '복통/통증 증상 호소',
    easy: { ko: '배 아파요.', pron: 'Bae apayo.', en: 'Stomach hurts.' },
    std:  { ko: '배가 너무 아파요.', pron: 'Baega neomu apayo.', en: 'My stomach hurts so much.' },
    pro:  { ko: '아침부터 복통과 어지러움이 심한데 진료를 받을 수 있을까요?', pron: 'Achimbuteo boktong-gwa eojireo-umi simhande jinryo-reul badeul su isseulkkayo?', en: 'I have severe stomach pain and dizziness since morning, can I see a doctor?' },
    tip: '병원이나 약국에서 증상을 호소할 때 씁니다.',
  },
  {
    id: 'tv-help-04', cat: 'help',
    title: '지갑 분실 알리기',
    easy: { ko: '지갑 잃어버렸어요.', pron: 'Jigap ireobeoryeosseoyo.', en: 'Lost wallet.' },
    std:  { ko: '지갑을 잃어버렸어요.', pron: 'Jigabeul ireobeoryeosseoyo.', en: 'I lost my wallet.' },
    pro:  { ko: '죄송합니다, 방금 제 검은색 가죽 지갑을 분실해서 신고하고 싶습니다.', pron: 'Joesonghamnida, banggeum je geomeunsaek gajuk jigabeul bunsilhaeseo singohago sipseumnida.', en: 'Excuse me, I just lost my black leather wallet and would like to file a report.' },
    tip: '분실물 센터나 경찰서에 분실 신고를 할 때 씁니다.',
  },
  {
    id: 'tv-help-05', cat: 'help',
    title: '택시 분실물 문의',
    easy: { ko: '택시에 폰 두고 내렸어요.', pron: 'Taeksie pon dugo naeryeosseoyo.', en: 'Left phone in taxi.' },
    std:  { ko: '핸드폰을 택시에 두고 내렸어요.', pron: 'Haendeopon-eul taeksie dugo naeryeosseoyo.', en: 'I left my phone in the taxi.' },
    pro:  { ko: '방금 내린 택시에 휴대전화를 두고 내렸는데, 기사님과 연락할 방법이 있을까요?', pron: 'Banggeum naerin taeksie hyudaewonhwa-reul dugo naeryeonneunde yeonlakhal bangbeobi isseulkkayo?', en: 'I left my phone in the taxi I just got off, is there any way to contact the driver?' },
    tip: '택시 영수증이나 결제 내역과 함께 분실을 알릴 때 씁니다.',
  },
  {
    id: 'tv-help-06', cat: 'help',
    title: '위급 상황 도움 요청',
    easy: { ko: '도와주세요!', pron: 'Dowajuseyo!', en: 'Help me!' },
    std:  { ko: '여기 좀 도와주세요!', pron: 'Yeogi jom dowajuseyo!', en: 'Please help me here!' },
    pro:  { ko: '위급한 상황입니다! 누구 경찰이나 구급차 좀 불러주세요!', pron: 'Wigeubhan sanghwang-imnida! Nugu gyeongchal-ina gubeupcha jom bulleojuseyo!', en: 'This is an emergency! Someone please call the police or an ambulance!' },
    tip: '위급한 상황에서 주변 사람들에게 즉각 도움을 청할 때 씁니다.',
  },
];
