import fs from 'node:fs';

const DICT = {
  "스스": { ko: "스스로", en: "by oneself; voluntarily", alt: ["스스", "스스로"] },
  "밖으": { ko: "밖", en: "outside", alt: ["밖으", "밖으로"] },
  "집으": { ko: "집", en: "house; home", alt: ["집으", "집으로"] },
  "앞으": { ko: "앞", en: "front", alt: ["앞으", "앞으로"] },
  "그대": { ko: "그대로", en: "as it is; intact", alt: ["그대", "그대로"] },
  "깨끗": { ko: "깨끗하다", en: "to be clean", alt: ["깨끗", "깨끗이", "깨끗한"] },
  "완충재": { ko: "완충재", en: "cushioning material; buffer" },
  "카멜레온": { ko: "카멜레온", en: "chameleon" },
  "열기": { ko: "열기", en: "heat; excitement" },
  "사막": { ko: "사막", en: "desert" },
  "안쪽": { ko: "안쪽", en: "inside; inner part" },
  "완충": { ko: "완충", en: "cushion; buffer" },
  "서서히": { ko: "서서히", en: "gradually; slowly" },
  "유도하": { ko: "유도하다", en: "to induce; to guide", alt: ["유도하", "유도하는", "유도하여"] },
  "불안": { ko: "불안", en: "anxiety; unease" },
  "잦은": { ko: "잦다", en: "to be frequent", alt: ["잦은"] },
  "내려": { ko: "내리다", en: "to descend; to get off", alt: ["내려"] },
  "서식지": { ko: "서식지", en: "habitat" },
  "피톤치드": { ko: "피톤치드", en: "phytoncide" },
  "부작용": { ko: "부작용", en: "side effect" },
  "발광": { ko: "발광", en: "luminescence; emitting light" },
  "대규모": { ko: "대규모", en: "large scale" },
  "들었다": { ko: "듣다", en: "to hear; to listen", alt: ["들었다"] },
  "공부방": { ko: "공부방", en: "study room" },
  "없었다": { ko: "없다", en: "to not exist; to lack", alt: ["없었다"] },
  "있었지": { ko: "있다", en: "to exist; to have", alt: ["있었지"] },
  "놋그릇": { ko: "놋그릇", en: "brassware; brass bowl" },
  "꺼냈다": { ko: "꺼내다", en: "to take out; to pull out", alt: ["꺼냈다"] },
  "글러브": { ko: "글러브", en: "glove; mitt" },
  "줄었다": { ko: "줄다", en: "to decrease; to diminish", alt: ["줄었다"] },
  "바닷물": { ko: "바닷물", en: "seawater" },
  "끌어올려": { ko: "끌어올리다", en: "to pull up; to raise", alt: ["끌어올려"] },
  "얼음": { ko: "얼음", en: "ice" },
  "상대방": { ko: "상대방", en: "counterpart; the other person" },
  "심리학": { ko: "심리학", en: "psychology" },
  "무거운": { ko: "무겁다", en: "to be heavy", alt: ["무거운"] },
  "이용하": { ko: "이용하다", en: "to use; to utilize", alt: ["이용하", "이용하는"] },
  "동물병원": { ko: "동물병원", en: "animal hospital; veterinary clinic" },
  "봉사자": { ko: "봉사자", en: "volunteer" },
  "참여할": { ko: "참여하다", en: "to participate", alt: ["참여할"] },
  "쓰지": { ko: "쓰다", en: "to use; to write", alt: ["쓰지"] },
  "손으": { ko: "손", en: "hand", alt: ["손으", "손으로"] },
  "음악회": { ko: "음악회", en: "concert; musical performance" },
  "내리": { ko: "내리다", en: "to fall; to descend", alt: ["내리는", "내리"] },
  "번에": { ko: "번", en: "time; turn", alt: ["번에"] },
  "컴퓨터": { ko: "컴퓨터", en: "computer" },
  "뜨거운": { ko: "뜨겁다", en: "to be hot", alt: ["뜨거운"] },
  "세상": { ko: "세상", en: "world; society" },
  "넣어": { ko: "넣다", en: "to put in; to insert", alt: ["넣어"] },
  "묻은": { ko: "묻다", en: "to be stained; to stick to", alt: ["묻은"] },
  "허리": { ko: "허리", en: "waist; lower back" },
  "차단하": { ko: "차단하다", en: "to block; to shut off", alt: ["차단하", "차단하는"] },
  "살균": { ko: "살균", en: "sterilization; disinfection" },
  "조리": { ko: "조리", en: "cooking; culinary art" },
  "감지기": { ko: "감지기", en: "detector; sensor" },
  "대화": { ko: "대화", en: "conversation; dialogue" },
  "규정": { ko: "규정", en: "rule; regulation" },
  "즉시": { ko: "즉시", en: "immediately; right away" },
  "심장": { ko: "심장", en: "heart" },
  "진입": { ko: "진입", en: "entry; admission" },
  "안전사고": { ko: "안전사고", en: "safety accident" },
  "지식": { ko: "지식", en: "knowledge" },
  "균형": { ko: "균형", en: "balance; equilibrium" },
  "활짝": { ko: "활짝", en: "widely; completely" },
  "이하": { ko: "이하", en: "or less; below" },
  "로봇": { ko: "로봇", en: "robot" },
  "실습": { ko: "실습", en: "practical training; practice" },
  "숲속": { ko: "숲속", en: "in the woods; forest" },
  "수강료": { ko: "수강료", en: "tuition; course fee" },
  "상관없": { ko: "상관없다", en: "to not matter; to be irrelevant", alt: ["상관없이", "상관없"] },
  "하며": { ko: "하다", en: "to do", alt: ["하며"] },
  "꽃밭": { ko: "꽃밭", en: "flower garden; flower bed" },
  "횡단보도": { ko: "횡단보도", en: "crosswalk; pedestrian crossing" },
  "바깥": { ko: "바깥", en: "outside; exterior" },
  "민간": { ko: "민간", en: "civilian; private sector" },
  "운영하": { ko: "운영하다", en: "to operate; to manage", alt: ["운영하", "운영하는"] },
  "일상생활": { ko: "일상생활", en: "daily life; everyday life" },
  "예산": { ko: "예산", en: "budget" },
  "질병": { ko: "질병", en: "disease; illness" },
  "나누": { ko: "나누다", en: "to divide; to share", alt: ["나누", "나누는"] },
  "잘게": { ko: "잘다", en: "to be small; to be fine", alt: ["잘게"] },
  "모래": { ko: "모래", en: "sand" },
  "영양분": { ko: "영양분", en: "nutrient; nourishing substance" },
  "약품": { ko: "약품", en: "medicine; chemical" },
  "나오": { ko: "나오다", en: "to come out; to emerge", alt: ["나오", "나오는"] },
  "활용하": { ko: "활용하다", en: "to utilize; to make use of", alt: ["활용하", "활용하는"] },
  "압력": { ko: "압력", en: "pressure" },
  "낮추": { ko: "낮추다", en: "to lower; to reduce", alt: ["낮추", "낮추는"] },
  "보이지": { ko: "보이다", en: "to be visible; to be seen", alt: ["보이지"] },
  "간격": { ko: "간격", en: "interval; gap" },
  "파장": { ko: "파장", en: "wavelength" },
  "장애물": { ko: "장애물", en: "obstacle; barrier" },
  "스며들지": { ko: "스며들다", en: "to permeate; to soak in", alt: ["스며들지"] },
  "페인트": { ko: "페인트", en: "paint" },
  "돌기": { ko: "돌기", en: "projection; protrusion" },
  "색소": { ko: "색소", en: "pigment; coloring" },
  "힘을": { ko: "힘", en: "strength; power", alt: ["힘을"] },
  "포식자": { ko: "포식자", en: "predator" },
  "시선": { ko: "시선", en: "gaze; line of sight" },
  "정교한": { ko: "정교하다", en: "to be elaborate; to be delicate", alt: ["정교한"] },
  "불만": { ko: "불만", en: "dissatisfaction; discontent" },
  "심어": { ko: "심다", en: "to plant", alt: ["심어"] },
  "복합": { ko: "복합", en: "combination; complex" },
  "폭우": { ko: "폭우", en: "heavy rain; downpour" },
  "경로": { ko: "경로", en: "route; path" },
  "장벽": { ko: "장벽", en: "barrier; wall" },
  "순환": { ko: "순환", en: "circulation; cycle" },
  "영양": { ko: "영양", en: "nutrition; nourishment" },
  "바꾸": { ko: "바꾸다", en: "to change; to exchange", alt: ["바꾸", "바꾸는"] },
  "사용하": { ko: "사용하다", en: "to use", alt: ["사용하", "사용하는"] },
  "안구": { ko: "안구", en: "eyeball" },
  "통행": { ko: "통행", en: "passage; traffic" },
  "심는": { ko: "심다", en: "to plant", alt: ["심는"] },
  "외곽": { ko: "외곽", en: "outskirts; suburb" },
  "올라": { ko: "오르다", en: "to climb; to rise", alt: ["올라"] },
  "살아가": { ko: "살아가다", en: "to live; to get by", alt: ["살아가", "살아가는"] },
  "물고기": { ko: "물고기", en: "fish" },
  "신뢰": { ko: "신뢰", en: "trust; faith" },
  "잎의": { ko: "잎", en: "leaf", alt: ["잎의", "잎이"] },
  "지반": { ko: "지반", en: "ground; foundation" },
  "유기물": { ko: "유기물", en: "organic matter" },
  "조상": { ko: "조상", en: "ancestor" },
  "국경": { ko: "국경", en: "national border; frontier" },
  "보호하": { ko: "보호하다", en: "to protect; to preserve", alt: ["보호하", "보호하는"] },
  "못하게": { ko: "못하다", en: "to prevent from; to be unable to", alt: ["못하게"] },
  "특성": { ko: "특성", en: "characteristic; property" },
  "발을": { ko: "발", en: "foot", alt: ["발을"] },
  "정자": { ko: "정자", en: "pavilion" },
  "화려한": { ko: "화려하다", en: "to be splendid; to be gorgeous", alt: ["화려한"] },
  "당시": { ko: "당시", en: "at that time; then" },
  "아무런": { ko: "아무런", en: "no such; any kind of" },
  "자랑스럽다": { ko: "자랑스럽다", en: "to be proud of" },
  "보았다": { ko: "보다", en: "to see; to watch", alt: ["보았다"] },
  "통쾌하다": { ko: "통쾌하다", en: "to be delightful; to be gratifying" },
  "망치": { ko: "망치", en: "hammer" },
  "손주": { ko: "손주", en: "grandchild" },
  "삼촌": { ko: "삼촌", en: "uncle" },
  "점퍼": { ko: "점퍼", en: "jumper; jacket" },
  "항아리": { ko: "항아리", en: "jar; pot" },
  "필통": { ko: "필통", en: "pencil case" },
  "극도": { ko: "극도", en: "extreme; maximum degree" },
  "집단": { ko: "집단", en: "group; collective" },
  "수산물": { ko: "수산물", en: "marine products; seafood" },
  "마련하": { ko: "마련하다", en: "to prepare; to arrange", alt: ["마련하", "마련하는"] },
  "관아": { ko: "관아", en: "government office in Joseon era" },
  "심리적": { ko: "심리적", en: "psychological" },
  "두고": { ko: "두다", en: "to put; to place", alt: ["두고"] },
  "노란": { ko: "노랗다", en: "to be yellow", alt: ["노란"] },
  "잎이": { ko: "잎", en: "leaf", alt: ["잎이"] },
  "버려": { ko: "버리다", en: "to throw away", alt: ["버려"] },
  "언제나": { ko: "언제나", en: "always; at all times" },
  "좋아하": { ko: "좋아하다", en: "to like; to fond of", alt: ["좋아하", "좋아하는"] },
  "들어오": { ko: "들어오다", en: "to come in; to enter", alt: ["들어오", "들어오는"] },
  "아무": { ko: "아무", en: "any; nobody" },
  "순간": { ko: "순간", en: "moment; instant" },
  "물은": { ko: "물", en: "water", alt: ["물은"] },
  "오지": { ko: "오다", en: "to come", alt: ["오지"] },
  "힘이": { ko: "힘", en: "strength; energy", alt: ["힘이"] },
  "밤마다": { ko: "밤", en: "night", alt: ["밤마다"] },
  "쥐고": { ko: "쥐다", en: "to hold; to clasp", alt: ["쥐고"] },
  "거품": { ko: "거품", en: "bubble; foam" },
  "손가락": { ko: "손가락", en: "finger" },
  "악기": { ko: "악기", en: "musical instrument" },
  "충격": { ko: "충격", en: "shock; impact" },
  "어깨": { ko: "어깨", en: "shoulder" },
  "효과적": { ko: "효과적", en: "effective" },
  "바퀴": { ko: "바퀴", en: "wheel" },
  "디자인": { ko: "디자인", en: "design" },
  "자외선": { ko: "자외선", en: "ultraviolet ray; UV" },
  "옷장": { ko: "옷장", en: "wardrobe; closet" },
  "실시간": { ko: "실시간", en: "real time" },
  "물방울": { ko: "물방울", en: "water drop; droplet" },
  "감동": { ko: "감동", en: "impression; deep emotion" },
  "사항": { ko: "사항", en: "matter; item" },
  "관람": { ko: "관람", en: "viewing; watching" },
  "행동": { ko: "행동", en: "behavior; action" },
  "관객": { ko: "관객", en: "audience; spectator" },
  "공연": { ko: "공연", en: "performance; show" },
  "이후": { ko: "이후", en: "after that; since" },
  "자정": { ko: "자정", en: "midnight" },
  "매월": { ko: "매월", en: "every month; monthly" },
  "도서": { ko: "도서", en: "books" },
  "투명한": { ko: "투명하다", en: "to be transparent; to be clear", alt: ["투명한"] },
  "통증": { ko: "통증", en: "pain; ache" },
  "원하": { ko: "원하다", en: "to want; to wish", alt: ["원하", "원하는"] },
  "컵을": { ko: "컵", en: "cup", alt: ["컵을"] },
  "보건소": { ko: "보건소", en: "public health center" },
  "경제": { ko: "경제", en: "economy" },
  "넘치": { ko: "넘치다", en: "to overflow", alt: ["넘치", "넘치는"] },
  "생명": { ko: "생명", en: "life" },
  "초등학생": { ko: "초등학생", en: "elementary student" },
  "인원": { ko: "인원", en: "number of people" },
  "도구": { ko: "도구", en: "tool; instrument" },
  "생태": { ko: "생태", en: "ecology" },
  "우선": { ko: "우선", en: "first; above all" },
  "빌려준다": { ko: "빌려주다", en: "to lend; to loan", alt: ["빌려준다"] },
  "무상": { ko: "무상", en: "free of charge" },
  "농사": { ko: "농사", en: "farming; agriculture" },
  "경험": { ko: "경험", en: "experience" },
  "멘토링": { ko: "멘토링", en: "mentoring" },
  "봉사단": { ko: "봉사단", en: "volunteer group" },
  "소정": { ko: "소정", en: "certain; prescribed" },
  "기사": { ko: "기사", en: "article; engineer; driver" },
  "기본": { ko: "기본", en: "basis; fundamental" },
  "단원": { ko: "단원", en: "unit; member" },
  "우수한": { ko: "우수하다", en: "to be excellent; to be superior", alt: ["우수한"] },
  "태도": { ko: "태도", en: "attitude; manner" },
  "돕기": { ko: "돕다", en: "to help", alt: ["돕기"] },
  "교통사고": { ko: "교통사고", en: "traffic accident" },
  "설치된": { ko: "설치되다", en: "to be installed", alt: ["설치된"] },
  "신형": { ko: "신형", en: "new model; new type" },
  "빠져": { ko: "빠지다", en: "to fall into; to escape", alt: ["빠져"] },
  "직원": { ko: "직원", en: "employee; staff" },
  "처리": { ko: "처리", en: "handling; processing" },
  "주방": { ko: "주방", en: "kitchen" },
  "발생하지": { ko: "발생하다", en: "to occur; to arise", alt: ["발생하지"] },
  "손쉽게": { ko: "손쉽다", en: "to be easy; to be simple", alt: ["손쉽게"] },
  "취약계층": { ko: "취약계층", en: "vulnerable group; underprivileged" },
  "저렴한": { ko: "저렴하다", en: "to be inexpensive; to be cheap", alt: ["저렴한"] },
  "벽돌": { ko: "벽돌", en: "brick" },
  "섞어": { ko: "섞다", en: "to mix; to blend", alt: ["섞어"] },
  "막아준다": { ko: "막아주다", en: "to block for; to protect from", alt: ["막아준다"] },
  "매연": { ko: "매연", en: "exhaust fumes; soot" },
  "쌓여": { ko: "쌓이다", en: "to pile up; to accumulate", alt: ["쌓여"] },
  "수질": { ko: "수질", en: "water quality" },
  "쉽지": { ko: "쉽다", en: "to be easy", alt: ["쉽지"] },
  "목재": { ko: "목재", en: "lumber; wood" },
  "얻을": { ko: "얻다", en: "to gain; to obtain", alt: ["얻을"] },
  "특수한": { ko: "특수하다", en: "to be special; to be distinct", alt: ["특수한"] },
  "나노": { ko: "나노", en: "nano" },
  "영하": { ko: "영하", en: "below zero; sub-zero" },
  "빛은": { ko: "빛", en: "light", alt: ["빛은"] },
  "자라": { ko: "자라다", en: "to grow", alt: ["자라"] },
  "산호": { ko: "산호", en: "coral" },
  "육지": { ko: "육지", en: "land" },
  "상처": { ko: "상처", en: "wound; scar" },
  "공유": { ko: "공유", en: "sharing" },
  "많았다": { ko: "많다", en: "to be many; to be much", alt: ["많았다"] },
  "자갈": { ko: "자갈", en: "gravel; pebble" },
  "창업": { ko: "창업", en: "start-up; business launch" },
  "떨어진다": { ko: "떨어지다", en: "to fall; to drop", alt: ["떨어진다"] },
  "늘리": { ko: "늘리다", en: "to increase; to expand", alt: ["늘리", "늘리는"] },
  "호흡": { ko: "호흡", en: "breathing; respiration" },
  "글자": { ko: "글자", en: "letter; character" },
  "호르몬": { ko: "호르몬", en: "hormone" },
  "과도한": { ko: "과도하다", en: "to be excessive; to be extreme", alt: ["과도한"] },
  "불빛": { ko: "불빛", en: "light; glow" },
  "발걸음": { ko: "발걸음", en: "step; pace" },
  "위생": { ko: "위생", en: "hygiene; sanitation" },
  "그물": { ko: "그물", en: "net; fishing net" },
  "농산물": { ko: "농산물", en: "agricultural produce" },
  "복원": { ko: "복원", en: "restoration; recovery" },
  "사라졌다": { ko: "사라지다", en: "to disappear; to vanish", alt: ["사라졌다"] },
  "수백": { ko: "수백", en: "hundreds" },
  "성능": { ko: "성능", en: "performance; capacity" },
  "털갈이": { ko: "털갈이", en: "molting; shedding" },
  "털이": { ko: "털", en: "hair; fur", alt: ["털이"] },
  "무더위": { ko: "무더위", en: "sweltering heat; heatwave" },
  "인위적": { ko: "인위적", en: "artificial" },
  "전부": { ko: "전부", en: "all; whole" },
  "펼쳐": { ko: "펼치다", en: "to unfold; to spread", alt: ["펼쳐"] },
  "손길": { ko: "손길", en: "helping hand; touch" },
  "마리": { ko: "마리", en: "counter for animals" },
  "버린": { ko: "버리다", en: "to throw away", alt: ["버린"] },
  "앞두고": { ko: "앞두다", en: "to have ahead; to be face to face with", alt: ["앞두고"] },
  "열렸다": { ko: "열리다", en: "to be opened; to be held", alt: ["열렸다"] }
};

const result = [];
const seen = new Set();

for (const [key, val] of Object.entries(DICT)) {
  if (seen.has(val.ko)) {
    const existing = result.find(r => r.ko === val.ko);
    if (existing && val.alt) {
      existing.alt = [...new Set([...(existing.alt || []), ...val.alt])];
    }
  } else {
    seen.add(val.ko);
    const item = { ko: val.ko, en: val.en };
    if (val.alt && val.alt.length) item.alt = val.alt;
    result.push(item);
  }
}

fs.writeFileSync('tools/batch2.json', JSON.stringify(result, null, 2), 'utf8');
console.log('Batch 2 entries ready:', result.length);
